# Generated by Django 5.0.6 on 2026-09-24 22:06

import apps.availability.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0003_secure_existing_accounts"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilitySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(
                        default=apps.availability.models.default_time_zone,
                        max_length=64,
                    ),
                ),
                ("min_duration", models.PositiveSmallIntegerField(default=50)),
                ("max_duration", models.PositiveSmallIntegerField(default=180)),
                (
                    "durations",
                    models.JSONField(
                        default=apps.availability.models.default_durations
                    ),
                ),
                ("buffer_minutes", models.PositiveSmallIntegerField(default=10)),
                ("min_notice_minutes", models.PositiveIntegerField(default=120)),
                ("horizon_days", models.PositiveSmallIntegerField(default=28)),
                ("start_step_minutes", models.PositiveSmallIntegerField(default=30)),
                ("hourly_rate_rub", models.PositiveIntegerField(default=3600)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="users.psychologistprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Правила записи",
                "db_table": "availability_settings",
            },
        ),
        migrations.CreateModel(
            name="DateOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("ranges", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_overrides",
                        to="users.psychologistprofile",
                    ),
                ),
            ],
            options={
                "db_table": "availability_date_override",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="TimeOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("note", models.CharField(blank=True, default="", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_off",
                        to="users.psychologistprofile",
                    ),
                ),
            ],
            options={
                "db_table": "availability_time_off",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_templates",
                        to="users.psychologistprofile",
                    ),
                ),
            ],
            options={
                "db_table": "availability_weekly_template",
                "ordering": ["valid_from", "id"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekday", models.PositiveSmallIntegerField()),
                ("start_minute", models.PositiveSmallIntegerField()),
                ("end_minute", models.PositiveSmallIntegerField()),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="availability.weeklytemplate",
                    ),
                ),
            ],
            options={
                "db_table": "availability_weekly_rule",
                "ordering": ["weekday", "start_minute"],
            },
        ),
        migrations.AddConstraint(
            model_name="dateoverride",
            constraint=models.UniqueConstraint(
                fields=("profile", "date"), name="availability_override_unique_date"
            ),
        ),
    ]
