# Generated by Django 5.0.6 on 2026-09-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("availability", "0002_import_legacy_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="availabilitysettings",
            name="intro_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="availabilitysettings",
            name="intro_price_rub",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
