# Generated by Django 5.0.6 on 2026-09-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("summary", models.CharField(blank=True, max_length=400)),
                ("body", models.TextField(help_text="Markdown")),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("anxiety", "Тревога"),
                            ("mood", "Настроение"),
                            ("stress", "Стресс и выгорание"),
                            ("sleep", "Сон"),
                            ("relationships", "Отношения"),
                            ("self", "Самооценка"),
                            ("loss", "Горе и утрата"),
                            ("therapy", "О терапии"),
                        ],
                        default="therapy",
                        max_length=32,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("cover", models.CharField(default="sky", max_length=16)),
                ("emoji", models.CharField(blank=True, max_length=8)),
                ("reading_minutes", models.PositiveSmallIntegerField(default=5)),
                (
                    "author_name",
                    models.CharField(
                        blank=True, default="Редакция aprosop", max_length=120
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-published_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="Practice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("summary", models.CharField(blank=True, max_length=400)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("breathing", "Дыхание"),
                            ("grounding", "Заземление"),
                            ("body", "Тело"),
                            ("journaling", "Записи"),
                            ("mindfulness", "Осознанность"),
                        ],
                        default="mindfulness",
                        max_length=16,
                    ),
                ),
                ("duration_minutes", models.PositiveSmallIntegerField(default=5)),
                ("steps", models.JSONField(blank=True, default=list)),
                ("pattern", models.JSONField(blank=True, null=True)),
                ("cover", models.CharField(default="mint", max_length=16)),
                ("emoji", models.CharField(blank=True, max_length=8)),
                ("order", models.PositiveSmallIntegerField(default=100)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
    ]
