# Generated by Django 5.0.6 on 2026-09-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_seed_starter_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="evidence_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("strong", "Сильная доказательная база"),
                    ("moderate", "Умеренная доказательная база"),
                    ("limited", "Ограниченные данные"),
                    ("practice", "Практический опыт"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="key_facts",
            field=models.JSONField(
                blank=True, default=list, help_text='[{"text": str, "refs": [int]}]'
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="reviewed_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='[{"title", "authors", "year", "publisher", "url", "doi"?, "kind"?}] — only verified links',
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="when_to_seek_help",
            field=models.TextField(blank=True, default="", help_text="Markdown"),
        ),
        migrations.AddField(
            model_name="practice",
            name="cautions",
            field=models.TextField(
                blank=True, default="", help_text="Markdown: when to stop or skip"
            ),
        ),
        migrations.AddField(
            model_name="practice",
            name="evidence_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("strong", "Сильная доказательная база"),
                    ("moderate", "Умеренная доказательная база"),
                    ("limited", "Ограниченные данные"),
                    ("practice", "Практический опыт"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="practice",
            name="mechanism",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Markdown: why it works, with [n] citations",
            ),
        ),
        migrations.AddField(
            model_name="practice",
            name="reviewed_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="practice",
            name="sources",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
