# Generated by Django 5.0.6 on 2026-09-27 17:16

import apps.content.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    """Markdown → HTML один раз (body остаётся резервной копией), topic → topics."""
    from apps.content.richtext import markdown_to_html

    Article = apps.get_model("content", "Article")
    for a in Article.objects.all().only("id", "body", "content", "topic", "topics"):
        fields = []
        if not a.content and a.body:
            a.content = markdown_to_html(a.body)
            fields.append("content")
        if not a.topics:
            a.topics = [a.topic or "therapy"]
            fields.append("topics")
        if fields:
            a.save(update_fields=fields)


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_specialist_articles_covers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Sanitized HTML (richtext.sanitize_html)",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="topics",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="article",
            name="body",
            field=models.TextField(
                blank=True, default="", help_text="Markdown (до 0007; резервная копия)"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="topic",
            field=models.CharField(
                choices=[
                    ("anxiety", "Тревога"),
                    ("mood", "Депрессия и настроение"),
                    ("stress", "Стресс и выгорание"),
                    ("sleep", "Сон"),
                    ("emotions", "Эмоции"),
                    ("self", "Самооценка"),
                    ("relationships", "Отношения"),
                    ("family", "Семья и дети"),
                    ("conflicts", "Конфликты"),
                    ("boundaries", "Границы"),
                    ("loneliness", "Одиночество"),
                    ("loss", "Горе и утрата"),
                    ("trauma", "Травма"),
                    ("addiction", "Зависимости"),
                    ("eating", "Пищевое поведение"),
                    ("work", "Работа и карьера"),
                    ("body", "Телесность"),
                    ("mindfulness", "Осознанность"),
                    ("teens", "Подростки"),
                    ("therapy", "О терапии"),
                ],
                default="therapy",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ArticleImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to=apps.content.models._image_path)),
                (
                    "image_md",
                    models.ImageField(upload_to=apps.content.models._image_md_path),
                ),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "content_article_image",
            },
        ),
        migrations.CreateModel(
            name="ArticleRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stars", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="content.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "content_article_rating",
            },
        ),
        migrations.AddConstraint(
            model_name="articlerating",
            constraint=models.UniqueConstraint(
                fields=("article", "user"), name="uniq_article_rating_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="articlerating",
            constraint=models.CheckConstraint(
                check=models.Q(("stars__gte", 1), ("stars__lte", 5)),
                name="article_rating_1_5",
            ),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
