# Generated by Django 5.0.6 on 2026-09-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_editors_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="language",
            field=models.CharField(
                choices=[
                    ("ru", "Русский"),
                    ("en", "English"),
                    ("uk", "Українська"),
                    ("be", "Беларуская"),
                    ("kk", "Қазақша"),
                    ("uz", "Oʻzbekcha"),
                    ("ky", "Кыргызча"),
                    ("hy", "Հայերեն"),
                    ("ka", "ქართული"),
                    ("az", "Azərbaycanca"),
                    ("ro", "Română"),
                    ("de", "Deutsch"),
                    ("es", "Español"),
                    ("fr", "Français"),
                ],
                db_index=True,
                default="ru",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="practice",
            name="language",
            field=models.CharField(
                choices=[
                    ("ru", "Русский"),
                    ("en", "English"),
                    ("uk", "Українська"),
                    ("be", "Беларуская"),
                    ("kk", "Қазақша"),
                    ("uz", "Oʻzbekcha"),
                    ("ky", "Кыргызча"),
                    ("hy", "Հայերեն"),
                    ("ka", "ქართული"),
                    ("az", "Azərbaycanca"),
                    ("ro", "Română"),
                    ("de", "Deutsch"),
                    ("es", "Español"),
                    ("fr", "Français"),
                ],
                db_index=True,
                default="ru",
                max_length=8,
            ),
        ),
    ]
