# Generated by Django 5.0.6 on 2026-09-24 22:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0003_secure_existing_accounts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("specialist", "Клиент и специалист"),
                            ("client_support", "Клиент и поддержка"),
                            ("specialist_support", "Специалист и поддержка"),
                            ("ai", "Клиент и ИИ-помощник"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "retention",
                    models.CharField(
                        choices=[("24h", "24 часа"), ("forever", "Бессрочно")],
                        default="forever",
                        max_length=8,
                    ),
                ),
                ("retention_changed_at", models.DateTimeField(blank=True, null=True)),
                ("support_read_at", models.DateTimeField(blank=True, null=True)),
                ("ai_consent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_message_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to="users.psychologistprofile",
                    ),
                ),
            ],
            options={
                "db_table": "chat_conversation",
            },
        ),
        migrations.CreateModel(
            name="ConversationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="chat.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_member",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sender_role",
                    models.CharField(
                        choices=[
                            ("client", "Клиент"),
                            ("specialist", "Специалист"),
                            ("support", "Поддержка"),
                            ("ai", "ИИ-помощник"),
                            ("system", "Система"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text", "Текст"),
                            ("voice", "Голосовое"),
                            ("file", "Файл"),
                            ("system", "Системное"),
                        ],
                        default="text",
                        max_length=8,
                    ),
                ),
                ("text_enc", models.BinaryField(blank=True, default=b"")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="HiddenMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hidden_for",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "db_table": "chat_hidden_message",
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_enc", models.BinaryField(blank=True, default=b"")),
                ("mime", models.CharField(max_length=100)),
                ("size", models.PositiveIntegerField()),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("peaks", models.JSONField(blank=True, default=list)),
                ("data_enc", models.BinaryField()),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachment",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "db_table": "chat_attachment",
            },
        ),
        migrations.CreateModel(
            name="AIDailyUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_ai_usage",
                "unique_together": {("user", "day")},
            },
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "specialist")),
                fields=("client", "specialist"),
                name="chat_unique_client_specialist",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "client_support")),
                fields=("client",),
                name="chat_unique_client_support",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "specialist_support")),
                fields=("specialist",),
                name="chat_unique_specialist_support",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "ai")),
                fields=("client",),
                name="chat_unique_client_ai",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conversationmember",
            unique_together={("conversation", "user")},
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="chat_messag_convers_3154fc_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hiddenmessage",
            unique_together={("message", "user")},
        ),
    ]
