# Generated by Django 5.0.6 on 2026-09-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="screen_protect",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="retention",
            field=models.CharField(
                choices=[
                    ("1h", "1 час"),
                    ("24h", "1 день"),
                    ("forever", "Выкл — хранить всегда"),
                ],
                default="forever",
                max_length=8,
            ),
        ),
    ]
