# Generated by Django 5.0.6 on 2026-09-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_files_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="view_once",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
