# Generated by Django 5.0.6 on 2026-09-24 17:55

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="psychologistprofile",
            name="approach",
            field=models.TextField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="psychologistprofile",
            name="experience_years",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_config",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[apps.users.models.validate_avatar_config],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="recovery_key_hash",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_hash",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
