# Generated by Django 5.0.6 on 2026-09-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_secure_existing_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="psychologistprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("", "Не указан"), ("female", "Женщина"), ("male", "Мужчина")],
                db_default="",
                default="",
                max_length=10,
            ),
        ),
    ]
