# Generated by Django 5.0.6 on 2026-09-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_psychologist_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Клиент"),
                    ("psychologist", "Психолог"),
                    ("admin", "Администратор"),
                    ("business", "HR компании"),
                ],
                default="client",
                max_length=20,
            ),
        ),
    ]
