# Generated by Django 5.0.6 on 2026-09-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alias_changed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="psychologistprofile",
            name="birth_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
