# Generated by Django 5.0.6 on 2026-09-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_birth_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="psychologistprofile",
            name="licensure",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="psychologistprofile",
            name="serves_countries",
            field=models.JSONField(blank=True, db_default=[], default=list),
        ),
    ]
