# Generated by Django 5.0.6 on 2026-09-24 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0002_initial"),
        ("users", "0003_secure_existing_accounts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="consultationsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["cancelled", "refunded"]), _negated=True
                ),
                fields=("psychologist_profile", "scheduled_at"),
                name="consultation_unique_active_start",
            ),
        ),
    ]
