# Generated by Django 5.0.6 on 2026-09-24 22:02

import apps.photos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0003_secure_existing_accounts"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialistPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        height_field="height",
                        upload_to=apps.photos.models._photo_path,
                        width_field="width",
                    ),
                ),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo",
                        to="users.psychologistprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото специалиста",
                "db_table": "photos_specialist_photo",
            },
        ),
    ]
