# Generated by Django 5.0.6 on 2026-09-26 08:54

import apps.circles.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0005_alter_user_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Circle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("anxiety", "Тревога"),
                            ("burnout", "Выгорание"),
                            ("breakup", "Расставание"),
                            ("grief", "Горе и утрата"),
                            ("parenting", "Родительство"),
                            ("self_esteem", "Самооценка"),
                            ("loneliness", "Одиночество"),
                            ("relocation", "Переезд и эмиграция"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(max_length=3000)),
                ("rules", models.TextField(blank=True, default="", max_length=2000)),
                (
                    "format",
                    models.CharField(
                        choices=[("series", "Цикл встреч"), ("single", "Одна встреча")],
                        default="series",
                        max_length=10,
                    ),
                ),
                ("meeting_minutes", models.PositiveSmallIntegerField(default=90)),
                ("capacity", models.PositiveSmallIntegerField(default=8)),
                (
                    "billing",
                    models.CharField(
                        choices=[
                            ("per_meeting", "За каждую встречу"),
                            ("series", "За весь цикл"),
                        ],
                        default="per_meeting",
                        max_length=12,
                    ),
                ),
                ("price_kopecks", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending", "На проверке"),
                            ("rejected", "Нужны правки"),
                            ("recruiting", "Набор"),
                            ("running", "Идёт"),
                            ("finished", "Завершён"),
                            ("cancelled", "Отменён"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("allow_real_faces", models.BooleanField(default=False)),
                (
                    "chat_retention",
                    models.CharField(
                        choices=[
                            ("forever", "Хранить всё время круга"),
                            ("24h", "Исчезают через 1 день"),
                            ("1h", "Исчезают через 1 час"),
                        ],
                        default="forever",
                        max_length=8,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_comment",
                    models.TextField(blank=True, default="", max_length=2000),
                ),
                (
                    "cancel_reason",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circles",
                        to="users.psychologistprofile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "circles_circle",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("index", models.PositiveSmallIntegerField()),
                ("starts_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Запланирована"),
                            ("live", "Идёт"),
                            ("done", "Прошла"),
                            ("missed", "Не состоялась"),
                            ("cancelled", "Отменена"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=10,
                    ),
                ),
                (
                    "room_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("host_joined_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("settled", models.BooleanField(default=False)),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="circles.circle",
                    ),
                ),
            ],
            options={
                "db_table": "circles_meeting",
                "ordering": ["starts_at"],
                "unique_together": {("circle", "index")},
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Участник"),
                            ("waitlist", "Лист ожидания"),
                            ("left", "Вышел"),
                            ("removed", "Удалён ведущим"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("pseudonym", models.CharField(max_length=40)),
                (
                    "handle",
                    models.CharField(
                        default=apps.circles.models.new_handle,
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("tone", models.CharField(default="lilac", max_length=10)),
                ("chat_muted", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("waitlisted_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("promote_failed_at", models.DateTimeField(blank=True, null=True)),
                ("chat_read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="circles.circle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circle_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "circles_membership",
                "ordering": ["joined_at"],
                "unique_together": {("circle", "pseudonym"), ("circle", "user")},
            },
        ),
        migrations.CreateModel(
            name="Charge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ref",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("amount_kopecks", models.BigIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charges",
                        to="circles.meeting",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges",
                        to="circles.membership",
                    ),
                ),
            ],
            options={
                "db_table": "circles_charge",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CircleMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Участник"),
                            ("host", "Ведущий"),
                            ("system", "Система"),
                        ],
                        max_length=8,
                    ),
                ),
                ("text_enc", models.BinaryField(blank=True, default=b"")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="circles.circle",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="circles.membership",
                    ),
                ),
            ],
            options={
                "db_table": "circles_message",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["circle", "created_at"],
                        name="circles_mes_circle__36cb03_idx",
                    )
                ],
            },
        ),
    ]
