# Generated by Django 5.0.6 on 2026-09-27 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circles", "0001_initial"),
        ("users", "0006_alias_changed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="circle",
            name="cohost",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cohosted_circles",
                to="users.psychologistprofile",
            ),
        ),
        migrations.AddField(
            model_name="circle",
            name="cohost_invited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="circle",
            name="cohost_share_percent",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="circle",
            name="cohost_status",
            field=models.CharField(
                blank=True,
                choices=[("invited", "Приглашён"), ("accepted", "Ко-терапевт")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="circlemessage",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Участник"),
                    ("host", "Ведущий"),
                    ("cohost", "Ко-терапевт"),
                    ("system", "Система"),
                ],
                max_length=8,
            ),
        ),
    ]
