# Generated by Django 5.0.6 on 2026-10-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_couples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='topic',
            field=models.CharField(choices=[('anxiety', 'Тревога'), ('burnout', 'Выгорание'), ('breakup', 'Расставание'), ('grief', 'Горе и утрата'), ('parenting', 'Родительство'), ('relationships', 'Отношения'), ('self_esteem', 'Самооценка'), ('loneliness', 'Одиночество'), ('relocation', 'Переезд и эмиграция')], db_index=True, max_length=20),
        ),
    ]
