/* eslint-disable */
// Generated by tools/headz/export_hands.py — do not edit.

/** character group → floating-hands GLB (both hands, minimal 21+5-bone skeleton each) */
export const HANDS_BY_GROUP: Record<string, string> = {
 "man": "/avatar/hands/man.glb",
 "woman": "/avatar/hands/woman.glb",
 "boy": "/avatar/hands/boy.glb",
 "oldman": "/avatar/hands/oldman.glb",
 "oldwoman": "/avatar/hands/oldwoman.glb",
 "girl": "/avatar/hands/boy.glb"
};
