# Generated by Django 5.0.6 on 2026-09-29 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("adult", "Подтвердил(а), что есть 18 лет"),
                            (
                                "health_data",
                                "Явное согласие на обработку сведений о здоровье",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("country", models.CharField(blank=True, default="", max_length=2)),
                ("version", models.CharField(blank=True, default="", max_length=20)),
                ("given_at", models.DateTimeField(auto_now_add=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Согласие",
                "verbose_name_plural": "Согласия",
                "db_table": "intl_consent",
                "indexes": [
                    models.Index(
                        fields=["user", "kind"], name="intl_consen_user_id_72fc73_idx"
                    )
                ],
            },
        ),
    ]
