import Link from "next/link";
import type { ReactNode } from "react";
import { Tbd, TbdBlock } from "./Placeholder";
import l from "@/components/landing/legal.module.css";

/**
 * English versions of the legal documents (by slug → section id). A courtesy translation of the Russian drafts;
 * everything a lawyer still has to write for foreign users (GDPR / UK GDPR / US state law) is marked
 * [to be completed]. Sections without an entry render as a single [to be completed] block.
 * See docs/INTERNATIONAL.md for what each market requires.
 */
export const LEGAL_EN: Record<string, Record<string, ReactNode>> = {
  privacy: {
    general: (
      <>
        <p>
          This policy describes how the Aprosop service (aprosop.ru) processes the data of its users — clients and specialists. The
          Russian version was prepared in line with Russian Federal Law No. 152-FZ “On Personal Data”.
        </p>
        <p>
          Operator: <Tbd what="name" />, tax ID <Tbd />, registration number <Tbd />, address <Tbd />. Full details are on the{" "}
          <Link href="/en/legal/requisites">“Company details”</Link> page.
        </p>
        <TbdBlock>
          Controller and representative for users in the EU/EEA and the UK (GDPR Art. 27), data protection officer if required.
        </TbdBlock>
      </>
    ),
    data: (
      <>
        <p>For clients:</p>
        <ul>
          <li>
            <strong>Name on the service</strong>, e.g. “quiet-whale-4821”. It is generated by the system and not linked to your real name.
          </li>
          <li>
            <strong>Password and recovery key</strong>, only as a hash: nobody, including us, can learn the password or key from it.
          </li>
          <li>
            <strong>Avatar settings</strong>: face shape, hairstyle, colours. A set of parameters, not a photo.
          </li>
          <li>
            <strong>Dialogues and calls</strong>: chat messages (under the retention rules you chose), the time, length and status of calls,
            and the specialist.
          </li>
          <li>
            <strong>Balance</strong>: top-ups, charges for calls, refunds.
          </li>
          <li>
            <strong>Preferences</strong>: interface language and the country you selected (used to show local crisis lines).
          </li>
        </ul>
        <p>
          For specialists, additionally: login details, application and public profile, qualification documents, payout details. Full
          list: <Tbd />
        </p>
        <TbdBlock>
          Messages in a mental-health context may reveal information about health, which is a special category of data under GDPR
          Art. 9: the explicit-consent mechanism for users in the EU/EEA and the UK.
        </TbdBlock>
      </>
    ),
    "not-store": (
      <div className={l.twoCol}>
        <div>
          <h3>About clients</h3>
          <p>Real name, email, phone number, date of birth, photo, documents.</p>
        </div>
        <div>
          <h3>About calls</h3>
          <p>Video, audio, the camera image and the content of the conversation.</p>
        </div>
      </div>
    ),
    call: (
      <>
        <p>
          The camera recognises your expressions right in your browser. Unless you choose to show your real face, the camera image never
          leaves your device: only the animated avatar is sent. The voice filter also runs on your device.
        </p>
        <p>
          Video and audio travel between browsers over an encrypted channel (WebRTC). Our server helps establish the connection but does
          not record the stream.
        </p>
        <p>
          Captions and “Text only” mode: speech is recognised on the speaker's device from the original voice, before the filter. The
          text goes directly to the other person over the same encrypted channel, bypassing our servers, and is not stored anywhere.
        </p>
        <p>
          <strong>An honest limitation.</strong> For a direct connection, browsers exchange network addresses, so technically a
          specialist may see your IP address, and our server sees it with every request, like any website.
        </p>
      </>
    ),
    purposes: <TbdBlock>Purposes of processing for each category of data.</TbdBlock>,
    grounds: (
      <TbdBlock>
        Legal bases for processing (Russian law; for EU/EEA and UK users — GDPR Art. 6 and Art. 9 conditions, e.g. explicit consent).
      </TbdBlock>
    ),
    terms: <TbdBlock>Retention periods by category of data.</TbdBlock>,
    share: (
      <>
        <p>
          Never for advertising or sale. A specialist sees your name on the service, your avatar and the messages in your dialogue with
          them. Payment happens on the payment service's side: your card number and name never reach us.
        </p>
        <TbdBlock>
          List of processors (hosting, payment service, AI provider for Tisha and others), where they are located, and the safeguards for
          cross-border transfers (including transfers of EU/UK users' data to Russia).
        </TbdBlock>
      </>
    ),
    device: (
      <p>
        Your browser stores login tokens, the interface language, the country you selected and the theme. More in the{" "}
        <Link href="/en/legal/cookies">cookie policy</Link>.
      </p>
    ),
    rights: (
      <>
        <p>
          The account settings have a “Delete account” button. After you confirm with your password, the account and its data are
          deleted. Data we are required by law to keep (for example, about payments) is kept for the statutory period: <Tbd />
        </p>
        <TbdBlock>
          How to exercise your rights (access, rectification, erasure, portability, objection, withdrawal of consent), response times, and
          the right to complain to a supervisory authority (EU/EEA, UK ICO) or under US state privacy laws.
        </TbdBlock>
      </>
    ),
    security: <TbdBlock>Organisational and technical security measures.</TbdBlock>,
    contacts: (
      <p>
        Send questions about your data to <a href="mailto:support@aprosop.ru">support@aprosop.ru</a>. You don't need to introduce
        yourself — your name on the service is enough if the question concerns your account.
      </p>
    ),
  },
  terms: {
    parties: (
      <>
        <p>
          This agreement is concluded between the operator of the service (<Tbd what="name" />, details on the{" "}
          <Link href="/en/legal/requisites">“Company details”</Link> page) and the user of aprosop.ru.
        </p>
        <TbdBlock>How the agreement is accepted and when it is concluded; governing law and language version that prevails.</TbdBlock>
      </>
    ),
    what: (
      <>
        <p>
          Aprosop helps you find a psychologist and talk to them anonymously in a dialogue and in video calls. The client appears under a
          generated name and a 3D avatar; the specialist under the name in their profile.
        </p>
        <p>
          Consultations are given by specialists whose profiles we have reviewed manually. The service provides the platform, booking,
          payment and a secure call.
        </p>
        <TbdBlock>
          Whether specialists are licensed to practise in the client's country or state, and how this is shown to clients outside Russia.
        </TbdBlock>
      </>
    ),
    emergency: (
      <p>
        A psychological consultation does not replace a doctor or emergency care. If you or someone near you is in danger, call your local
        emergency number (112 in Europe, 911 in the US and Canada, 999 in the UK) or a crisis line in your country — see{" "}
        <a href="https://findahelpline.com" target="_blank" rel="noopener noreferrer">
          findahelpline.com
        </a>
        .
      </p>
    ),
    age: (
      <p>
        The service is for adults. By creating an account you confirm that you are at least 18 years old. If you are younger, please
        talk to an adult you trust or call a helpline for young people in your country.
      </p>
    ),
    account: (
      <ul>
        <li>Only a password is needed to sign up. Your name and recovery key are created automatically.</li>
        <li>
          The recovery key is shown once. If you lose both the password and the key, access can't be restored: we don't know who you are
          and can't verify it.
        </li>
        <li>Don't share your password or key with others.</li>
        <li>You can delete your account in the settings at any time.</li>
      </ul>
    ),
    sessions: (
      <ul>
        <li>The price of a call is shown in the specialist's profile before booking. Prices are in Russian roubles.</li>
        <li>You can book free time no sooner than an hour ahead.</li>
        <li>You can cancel a call in the dialogue before it starts; free of charge up to 24 hours before.</li>
        <li>
          For refunds for a cancelled call, write to <a href="mailto:support@aprosop.ru">support@aprosop.ru</a> and give your name on the
          service.
        </li>
        <li>You can join a call 10 minutes before it starts and until it ends.</li>
      </ul>
    ),
    conduct: (
      <ul>
        <li>Don't record calls or take screenshots without the other person's consent.</li>
        <li>Don't try to find out who is behind an avatar, and don't ask the other person to reveal their identity.</li>
        <li>Be respectful. Threats and insults lead to the account being blocked.</li>
      </ul>
    ),
    specialists: (
      <ul>
        <li>The information in the application must be truthful. A profile appears in the catalogue after a manual review.</li>
        <li>We may suspend a profile if the information isn't confirmed or there are justified complaints.</li>
        <li>The specialist follows professional ethics and confidentiality and does not try to identify the client.</li>
        <li>
          Sign-up: <Link href="/en/join">specialist application</Link>.
        </li>
      </ul>
    ),
    paid: (
      <p>
        Terms for paying for calls and topping up the balance are set out in the <Link href="/en/legal/offer">public offer</Link> and the{" "}
        <Link href="/en/legal/refunds">refund policy</Link>.
      </p>
    ),
    changes: (
      <p>
        If the terms change, we will update this page and the date at the top. How we handle data is described in the{" "}
        <Link href="/en/legal/privacy">privacy policy</Link>. Send questions to <a href="mailto:support@aprosop.ru">support@aprosop.ru</a>.
      </p>
    ),
  },
};
