# Generated by Django 5.0.6 on 2026-09-26 08:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "legal_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("inn", models.CharField(blank=True, default="", max_length=12)),
                (
                    "contact_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "contact_email",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("pilot", "Пилот"),
                            ("standard", "Стандарт"),
                            ("enterprise", "Корпоративный"),
                        ],
                        default="pilot",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Работает"),
                            ("paused", "Приостановлена"),
                            ("closed", "Договор закрыт"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=12,
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Компания",
                "db_table": "business_company",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CodeBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=80)),
                ("count", models.PositiveIntegerField()),
                ("revoked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="business.company",
                    ),
                ),
            ],
            options={
                "db_table": "business_code_batch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanyAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, default="", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("must_change_password", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admins",
                        to="business.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "HR-администратор",
                "db_table": "business_company_admin",
            },
        ),
        migrations.CreateModel(
            name="EmployeeCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=64, unique=True)),
                ("encrypted", models.BinaryField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Не использован"),
                            ("used", "Использован"),
                            ("revoked", "Отозван"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="business.codebatch",
                    ),
                ),
            ],
            options={
                "db_table": "business_employee_code",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                ("amount_kopecks", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Выставлен"),
                            ("paid", "Оплачен"),
                            ("canceled", "Отменён"),
                        ],
                        db_index=True,
                        default="issued",
                        max_length=10,
                    ),
                ),
                ("requested_by_company", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="business.company",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "business_invoice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=160)),
                (
                    "contact_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("contact", models.CharField(max_length=160)),
                ("employees", models.PositiveIntegerField(blank=True, null=True)),
                ("message", models.TextField(blank=True, default="", max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В работе"),
                            ("done", "Закрыта"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=12,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="business.company",
                    ),
                ),
            ],
            options={
                "db_table": "business_lead",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Забота о сотрудниках", max_length=120),
                ),
                ("amount_kopecks", models.BigIntegerField(blank=True, null=True)),
                (
                    "calls_limit",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("month", "Месяц"),
                            ("quarter", "Квартал"),
                            ("year", "Год"),
                        ],
                        default="month",
                        max_length=10,
                    ),
                ),
                ("services", models.JSONField(default=list)),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("expires_on", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="business.company",
                    ),
                ),
            ],
            options={
                "db_table": "business_program",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code_ref", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Действует"), ("ended", "Завершено")],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("joined_month", models.DateField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="business.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="business.program",
                    ),
                ),
            ],
            options={
                "db_table": "business_enrollment",
            },
        ),
        migrations.AddField(
            model_name="codebatch",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="business.program",
            ),
        ),
        migrations.CreateModel(
            name="Charge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("service", models.CharField(default="calls", max_length=10)),
                ("ref", models.UUIDField(unique=True)),
                ("covered_kopecks", models.BigIntegerField()),
                ("returned_kopecks", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Заморожено"),
                            ("settled", "Списано"),
                            ("returned", "Возвращено"),
                        ],
                        db_index=True,
                        default="reserved",
                        max_length=10,
                    ),
                ),
                ("period_month", models.DateField(db_index=True)),
                ("topic", models.CharField(blank=True, default="other", max_length=20)),
                ("minutes", models.PositiveSmallIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="business.company",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="business.enrollment",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="business.program",
                    ),
                ),
            ],
            options={
                "db_table": "business_charge",
            },
        ),
    ]
