/* eslint-disable */
// Generated by tools/headz/build.mjs — do not edit.
import type { HeadzCatalog } from "./types";

export const CATALOG: HeadzCatalog = {
 "version": "6728b157ba",
 "bases": [
  {
   "id": "woman-light",
   "group": "woman",
   "tone": "light",
   "face": "/avatar/headz/woman-light/face.glb",
   "lod": "/avatar/headz/woman-light/face-lod.glb",
   "bytes": 477852,
   "tris": 21368,
   "skin": "#e18d72",
   "hair": "#efb974",
   "iris": "#015d74",
   "defaults": {
    "hair": "005"
   }
  },
  {
   "id": "woman-medium",
   "group": "woman",
   "tone": "medium",
   "face": "/avatar/headz/woman-medium/face.glb",
   "lod": "/avatar/headz/woman-medium/face-lod.glb",
   "bytes": 527172,
   "tris": 22085,
   "skin": "#a96248",
   "hair": "#140505",
   "iris": "#3f3027",
   "defaults": {
    "hair": "010"
   }
  },
  {
   "id": "woman-dark",
   "group": "woman",
   "tone": "dark",
   "face": "/avatar/headz/woman-dark/face.glb",
   "lod": "/avatar/headz/woman-dark/face-lod.glb",
   "bytes": 527156,
   "tris": 22085,
   "skin": "#743928",
   "hair": "#140505",
   "iris": "#3f3027",
   "defaults": {
    "hair": "010"
   }
  },
  {
   "id": "man-light",
   "group": "man",
   "tone": "light",
   "face": "/avatar/headz/man-light/face.glb",
   "lod": "/avatar/headz/man-light/face-lod.glb",
   "bytes": 499992,
   "tris": 22168,
   "skin": "#ba6956",
   "hair": "#0a0504",
   "iris": "#2c1005",
   "defaults": {
    "hair": "001"
   }
  },
  {
   "id": "man-medium",
   "group": "man",
   "tone": "medium",
   "face": "/avatar/headz/man-medium/face.glb",
   "lod": "/avatar/headz/man-medium/face-lod.glb",
   "bytes": 542196,
   "tris": 21048,
   "skin": "#ae674f",
   "hair": "#141414",
   "iris": "#070201",
   "defaults": {
    "beard": "moustache-4",
    "hair": "001"
   }
  },
  {
   "id": "man-dark",
   "group": "man",
   "tone": "dark",
   "face": "/avatar/headz/man-dark/face.glb",
   "lod": "/avatar/headz/man-dark/face-lod.glb",
   "bytes": 542196,
   "tris": 21048,
   "skin": "#68382a",
   "hair": "#141414",
   "iris": "#070201",
   "defaults": {
    "beard": "moustache-4",
    "hair": "001"
   }
  },
  {
   "id": "girl-light",
   "group": "girl",
   "tone": "light",
   "face": "/avatar/headz/girl-light/face.glb",
   "lod": "/avatar/headz/girl-light/face-lod.glb",
   "bytes": 754596,
   "tris": 19960,
   "skin": "#f2c6ba",
   "hair": "#260e0d",
   "iris": "#a4c1b9",
   "defaults": {
    "hair": "1"
   }
  },
  {
   "id": "girl-medium",
   "group": "girl",
   "tone": "medium",
   "face": "/avatar/headz/girl-medium/face.glb",
   "lod": "/avatar/headz/girl-medium/face-lod.glb",
   "bytes": 969528,
   "tris": 19280,
   "skin": "#ab8a7b",
   "hair": "#260e0d",
   "iris": "#c0a19a",
   "defaults": {
    "hair": "3"
   }
  },
  {
   "id": "girl-dark",
   "group": "girl",
   "tone": "dark",
   "face": "/avatar/headz/girl-dark/face.glb",
   "lod": "/avatar/headz/girl-dark/face-lod.glb",
   "bytes": 964596,
   "tris": 19280,
   "skin": "#9a796e",
   "hair": "#72351c",
   "iris": "#c0a19a",
   "defaults": {
    "hair": "3"
   }
  },
  {
   "id": "boy-light",
   "group": "boy",
   "tone": "light",
   "face": "/avatar/headz/boy-light/face.glb",
   "lod": "/avatar/headz/boy-light/face-lod.glb",
   "bytes": 931968,
   "tris": 25108,
   "skin": "#f0c5b2",
   "hair": "#dba769",
   "iris": "#bc938a",
   "defaults": {
    "hair": "5"
   }
  },
  {
   "id": "boy-medium",
   "group": "boy",
   "tone": "medium",
   "face": "/avatar/headz/boy-medium/face.glb",
   "lod": "/avatar/headz/boy-medium/face-lod.glb",
   "bytes": 843292,
   "tris": 25108,
   "skin": "#d7af9b",
   "hair": "#260e0d",
   "iris": "#bc938a",
   "defaults": {
    "hair": "6"
   }
  },
  {
   "id": "boy-dark",
   "group": "boy",
   "tone": "dark",
   "face": "/avatar/headz/boy-dark/face.glb",
   "lod": "/avatar/headz/boy-dark/face-lod.glb",
   "bytes": 843284,
   "tris": 25108,
   "skin": "#b69382",
   "hair": "#72351c",
   "iris": "#bc938a",
   "defaults": {
    "hair": "2"
   }
  },
  {
   "id": "oldwoman-light",
   "group": "oldwoman",
   "tone": "light",
   "face": "/avatar/headz/oldwoman-light/face.glb",
   "lod": "/avatar/headz/oldwoman-light/face-lod.glb",
   "bytes": 858748,
   "tris": 33348,
   "skin": "#c5a093",
   "hair": "#cecbc7",
   "iris": "#8fbed4",
   "defaults": {
    "hair": "9"
   }
  },
  {
   "id": "oldwoman-medium",
   "group": "oldwoman",
   "tone": "medium",
   "face": "/avatar/headz/oldwoman-medium/face.glb",
   "lod": "/avatar/headz/oldwoman-medium/face-lod.glb",
   "bytes": 1051712,
   "tris": 33884,
   "skin": "#91796b",
   "hair": "#cecbc7",
   "iris": "#ab8c89",
   "defaults": {
    "hair": "1"
   }
  },
  {
   "id": "oldwoman-dark",
   "group": "oldwoman",
   "tone": "dark",
   "face": "/avatar/headz/oldwoman-dark/face.glb",
   "lod": "/avatar/headz/oldwoman-dark/face-lod.glb",
   "bytes": 1050468,
   "tris": 33884,
   "skin": "#856b60",
   "hair": "#cecbc7",
   "iris": "#ab8c89",
   "defaults": {
    "hair": "1"
   }
  },
  {
   "id": "oldman-light",
   "group": "oldman",
   "tone": "light",
   "face": "/avatar/headz/oldman-light/face.glb",
   "lod": "/avatar/headz/oldman-light/face-lod.glb",
   "bytes": 850988,
   "tris": 33244,
   "skin": "#e8bdae",
   "hair": "#cecbc7",
   "iris": "#8fbed4",
   "defaults": {
    "hair": "4"
   }
  },
  {
   "id": "oldman-medium",
   "group": "oldman",
   "tone": "medium",
   "face": "/avatar/headz/oldman-medium/face.glb",
   "lod": "/avatar/headz/oldman-medium/face-lod.glb",
   "bytes": 747456,
   "tris": 30596,
   "skin": "#ac9383",
   "hair": "#cecbc7",
   "iris": "#a6938a",
   "defaults": {
    "hair": "5"
   }
  },
  {
   "id": "oldman-dark",
   "group": "oldman",
   "tone": "dark",
   "face": "/avatar/headz/oldman-dark/face.glb",
   "lod": "/avatar/headz/oldman-dark/face-lod.glb",
   "bytes": 745000,
   "tris": 30596,
   "skin": "#9c8175",
   "hair": "#cecbc7",
   "iris": "#a6938a",
   "defaults": {
    "hair": "4"
   }
  }
 ],
 "options": {
  "boy": {
   "hair": [
    {
     "id": "1",
     "files": {
      "boy-dark": "/avatar/headz/boy/hair-1-c88a1e89.glb",
      "boy-light": "/avatar/headz/boy/hair-1-c88a1e89.glb",
      "boy-medium": "/avatar/headz/boy/hair-1-c88a1e89.glb"
     },
     "color": "#72351c",
     "bytes": 38764,
     "tris": 7999
    },
    {
     "id": "2",
     "files": {
      "boy-dark": "/avatar/headz/boy/hair-2-e63db238.glb",
      "boy-light": "/avatar/headz/boy/hair-2-e63db238.glb",
      "boy-medium": "/avatar/headz/boy/hair-2-e63db238.glb"
     },
     "color": "#72351c",
     "bytes": 81928,
     "tris": 17662
    },
    {
     "id": "3",
     "files": {
      "boy-dark": "/avatar/headz/boy/hair-3-a9c85fae.glb",
      "boy-light": "/avatar/headz/boy/hair-3-a9c85fae.glb",
      "boy-medium": "/avatar/headz/boy/hair-3-a9c85fae.glb"
     },
     "color": "#72351c",
     "bytes": 40804,
     "tris": 8000
    },
    {
     "id": "4",
     "files": {
      "boy-dark": "/avatar/headz/boy/hair-4-ad6e41f4.glb",
      "boy-light": "/avatar/headz/boy/hair-4-ad6e41f4.glb",
      "boy-medium": "/avatar/headz/boy/hair-4-ad6e41f4.glb"
     },
     "color": "#72351c",
     "bytes": 114756,
     "tris": 24838
    },
    {
     "id": "5",
     "files": {
      "boy-dark": "/avatar/headz/boy/hair-5-ef6a3d0e.glb",
      "boy-light": "/avatar/headz/boy/hair-5-ef6a3d0e.glb",
      "boy-medium": "/avatar/headz/boy/hair-5-ef6a3d0e.glb"
     },
     "color": "#72351c",
     "bytes": 38036,
     "tris": 8000
    },
    {
     "id": "6",
     "files": {
      "boy-dark": "/avatar/headz/boy/hair-6-85f73f52.glb",
      "boy-light": "/avatar/headz/boy/hair-6-85f73f52.glb",
      "boy-medium": "/avatar/headz/boy/hair-6-8e2c31c4.glb"
     },
     "color": "#72351c",
     "bytes": 40344,
     "tris": 7999
    },
    {
     "id": "7",
     "files": {
      "boy-dark": "/avatar/headz/boy/hair-7-8b91df4b.glb",
      "boy-light": "/avatar/headz/boy/hair-7-8b91df4b.glb",
      "boy-medium": "/avatar/headz/boy/hair-7-8b91df4b.glb"
     },
     "color": "#72351c",
     "bytes": 41316,
     "tris": 7999
    },
    {
     "id": "8",
     "files": {
      "boy-dark": "/avatar/headz/boy/hair-8-a4fc6f40.glb",
      "boy-light": "/avatar/headz/boy/hair-8-a4fc6f40.glb",
      "boy-medium": "/avatar/headz/boy/hair-8-a4fc6f40.glb"
     },
     "color": "#72351c",
     "bytes": 38888,
     "tris": 8000
    },
    {
     "id": "9",
     "files": {
      "boy-dark": "/avatar/headz/boy/hair-9-ca7d165e.glb",
      "boy-light": "/avatar/headz/boy/hair-9-ca7d165e.glb",
      "boy-medium": "/avatar/headz/boy/hair-9-ca7d165e.glb"
     },
     "color": "#72351c",
     "bytes": 86964,
     "tris": 18698
    },
    {
     "id": "10",
     "files": {
      "boy-dark": "/avatar/headz/boy/hair-10-f08be77b.glb",
      "boy-light": "/avatar/headz/boy/hair-10-f08be77b.glb",
      "boy-medium": "/avatar/headz/boy/hair-10-f08be77b.glb"
     },
     "color": "#72351c",
     "bytes": 26500,
     "tris": 6080
    }
   ],
   "beard": [],
   "eyewear": [
    {
     "id": "eyeglasses-1",
     "files": {
      "boy-dark": "/avatar/headz/boy/eyewear-eyeglasses-1-db3a0c74.glb",
      "boy-light": "/avatar/headz/boy/eyewear-eyeglasses-1-db3a0c74.glb",
      "boy-medium": "/avatar/headz/boy/eyewear-eyeglasses-1-db3a0c74.glb"
     },
     "color": "#1d1d1d",
     "bytes": 25324,
     "tris": 5000
    },
    {
     "id": "eyeglasses-2",
     "files": {
      "boy-dark": "/avatar/headz/boy/eyewear-eyeglasses-2-763b0d31.glb",
      "boy-light": "/avatar/headz/boy/eyewear-eyeglasses-2-763b0d31.glb",
      "boy-medium": "/avatar/headz/boy/eyewear-eyeglasses-2-763b0d31.glb"
     },
     "color": "#d4f2ff",
     "bytes": 22612,
     "tris": 5000
    }
   ],
   "headwear": [
    {
     "id": "beanie-blue-spike",
     "files": {
      "boy-dark": "/avatar/headz/boy/headwear-beanie-blue-spike-69a6161a.glb",
      "boy-light": "/avatar/headz/boy/headwear-beanie-blue-spike-69a6161a.glb",
      "boy-medium": "/avatar/headz/boy/headwear-beanie-blue-spike-69a6161a.glb"
     },
     "color": "#b58900",
     "bytes": 24396,
     "tris": 5000,
     "rims": {
      "boy-dark": [
       0.207,
       -0.703
      ],
      "boy-light": [
       0.207,
       -0.703
      ],
      "boy-medium": [
       0.207,
       -0.703
      ]
     }
    },
    {
     "id": "beanie-yellow",
     "files": {
      "boy-dark": "/avatar/headz/boy/headwear-beanie-yellow-ef54e0b8.glb",
      "boy-light": "/avatar/headz/boy/headwear-beanie-yellow-ef54e0b8.glb",
      "boy-medium": "/avatar/headz/boy/headwear-beanie-yellow-ef54e0b8.glb"
     },
     "color": "#313131",
     "bytes": 23260,
     "tris": 5000,
     "rims": {
      "boy-dark": [
       0.863,
       -0.523
      ],
      "boy-light": [
       0.863,
       -0.523
      ],
      "boy-medium": [
       0.863,
       -0.523
      ]
     }
    },
    {
     "id": "cap",
     "files": {
      "boy-dark": "/avatar/headz/boy/headwear-cap-ded53a9c.glb",
      "boy-light": "/avatar/headz/boy/headwear-cap-ded53a9c.glb",
      "boy-medium": "/avatar/headz/boy/headwear-cap-ded53a9c.glb"
     },
     "color": "#273767",
     "bytes": 23928,
     "tris": 5000,
     "rims": {
      "boy-dark": [
       0.46,
       -0.174
      ],
      "boy-light": [
       0.46,
       -0.174
      ],
      "boy-medium": [
       0.46,
       -0.174
      ]
     }
    },
    {
     "id": "hat",
     "files": {
      "boy-dark": "/avatar/headz/boy/headwear-hat-c3131461.glb",
      "boy-light": "/avatar/headz/boy/headwear-hat-c3131461.glb",
      "boy-medium": "/avatar/headz/boy/headwear-hat-c3131461.glb"
     },
     "color": "#5d4288",
     "bytes": 22580,
     "tris": 5000,
     "rims": {
      "boy-dark": [
       0.748,
       -0.393
      ],
      "boy-light": [
       0.748,
       -0.393
      ],
      "boy-medium": [
       0.748,
       -0.393
      ]
     }
    }
   ],
   "earrings": []
  },
  "girl": {
   "hair": [
    {
     "id": "1",
     "files": {
      "girl-dark": "/avatar/headz/girl/hair-1-681e48cc.glb",
      "girl-light": "/avatar/headz/girl/hair-1-6aa31b29.glb",
      "girl-medium": "/avatar/headz/girl/hair-1-d77963a0.glb"
     },
     "color": "#72351c",
     "bytes": 42576,
     "tris": 7998
    },
    {
     "id": "2",
     "files": {
      "girl-dark": "/avatar/headz/girl/hair-2-fe80aa74.glb",
      "girl-light": "/avatar/headz/girl/hair-2-4c51f7cd.glb",
      "girl-medium": "/avatar/headz/girl/hair-2-6e122c20.glb"
     },
     "color": "#72351c",
     "bytes": 40136,
     "tris": 7999
    },
    {
     "id": "3",
     "files": {
      "girl-dark": "/avatar/headz/girl/hair-3-ca544a0f.glb",
      "girl-light": "/avatar/headz/girl/hair-3-545d3025.glb",
      "girl-medium": "/avatar/headz/girl/hair-3-b047b8a4.glb"
     },
     "color": "#72351c",
     "bytes": 41028,
     "tris": 7999
    },
    {
     "id": "4",
     "files": {
      "girl-dark": "/avatar/headz/girl/hair-4-0a2f214f.glb",
      "girl-light": "/avatar/headz/girl/hair-4-7e7b3f00.glb",
      "girl-medium": "/avatar/headz/girl/hair-4-9c2d9e18.glb"
     },
     "color": "#72351c",
     "bytes": 39076,
     "tris": 8000
    },
    {
     "id": "5",
     "files": {
      "girl-dark": "/avatar/headz/girl/hair-5-18b4d0a2.glb",
      "girl-light": "/avatar/headz/girl/hair-5-69f30566.glb",
      "girl-medium": "/avatar/headz/girl/hair-5-ae7f21c3.glb"
     },
     "color": "#72351c",
     "bytes": 39848,
     "tris": 8000
    },
    {
     "id": "6",
     "files": {
      "girl-dark": "/avatar/headz/girl/hair-6-7e5955d8.glb",
      "girl-light": "/avatar/headz/girl/hair-6-18027400.glb",
      "girl-medium": "/avatar/headz/girl/hair-6-70e56811.glb"
     },
     "color": "#72351c",
     "bytes": 42036,
     "tris": 8000
    },
    {
     "id": "7",
     "files": {
      "girl-dark": "/avatar/headz/girl/hair-7-54037aa7.glb",
      "girl-light": "/avatar/headz/girl/hair-7-a8f7a6cd.glb",
      "girl-medium": "/avatar/headz/girl/hair-7-fdfec2ac.glb"
     },
     "color": "#72351c",
     "bytes": 42872,
     "tris": 7999
    },
    {
     "id": "8",
     "files": {
      "girl-dark": "/avatar/headz/girl/hair-8-0b80ec17.glb",
      "girl-light": "/avatar/headz/girl/hair-8-69717676.glb",
      "girl-medium": "/avatar/headz/girl/hair-8-bd999ac3.glb"
     },
     "color": "#72351c",
     "bytes": 31052,
     "tris": 6864
    },
    {
     "id": "9",
     "files": {
      "girl-dark": "/avatar/headz/girl/hair-9-9a7a3b5c.glb",
      "girl-light": "/avatar/headz/girl/hair-9-f7f0f05c.glb",
      "girl-medium": "/avatar/headz/girl/hair-9-500ad0d8.glb"
     },
     "color": "#e7c870",
     "bytes": 44352,
     "tris": 7999
    },
    {
     "id": "10",
     "files": {
      "girl-light": "/avatar/headz/girl/hair-10-9137c7fe.glb"
     },
     "color": "#260e0d",
     "bytes": 39508,
     "tris": 7999
    }
   ],
   "beard": [],
   "eyewear": [
    {
     "id": "glasses-blue",
     "files": {
      "girl-dark": "/avatar/headz/girl/eyewear-glasses-blue-997ccefb.glb",
      "girl-light": "/avatar/headz/girl/eyewear-glasses-blue-ace6a307.glb",
      "girl-medium": "/avatar/headz/girl/eyewear-glasses-blue-e9998a9c.glb"
     },
     "color": "#02070d",
     "bytes": 23356,
     "tris": 5000
    },
    {
     "id": "glasses-red",
     "files": {
      "girl-dark": "/avatar/headz/girl/eyewear-glasses-red-4f0f8ed0.glb",
      "girl-light": "/avatar/headz/girl/eyewear-glasses-red-05f97219.glb",
      "girl-medium": "/avatar/headz/girl/eyewear-glasses-red-7234ee0b.glb"
     },
     "color": "#a11100",
     "bytes": 22688,
     "tris": 5000
    }
   ],
   "headwear": [
    {
     "id": "beanie-pink",
     "files": {
      "girl-dark": "/avatar/headz/girl/headwear-beanie-pink-4ebeee14.glb",
      "girl-light": "/avatar/headz/girl/headwear-beanie-pink-540ea8e3.glb",
      "girl-medium": "/avatar/headz/girl/headwear-beanie-pink-1bec5d9a.glb"
     },
     "color": "#ff7aa1",
     "bytes": 23092,
     "tris": 4999,
     "rims": {
      "girl-dark": [
       0.875,
       -0.65
      ],
      "girl-light": [
       0.908,
       -0.686
      ],
      "girl-medium": [
       0.874,
       -0.651
      ]
     }
    },
    {
     "id": "cap-yellow",
     "files": {
      "girl-dark": "/avatar/headz/girl/headwear-cap-yellow-c9359bc2.glb",
      "girl-light": "/avatar/headz/girl/headwear-cap-yellow-eb21d5b9.glb",
      "girl-medium": "/avatar/headz/girl/headwear-cap-yellow-cf493145.glb"
     },
     "color": "#000000",
     "bytes": 24568,
     "tris": 5000,
     "rims": {
      "girl-dark": [
       0.607,
       -0.288
      ],
      "girl-light": [
       0.67,
       -0.204
      ],
      "girl-medium": [
       0.607,
       -0.288
      ]
     }
    },
    {
     "id": "hat-pink",
     "files": {
      "girl-dark": "/avatar/headz/girl/headwear-hat-pink-3182f24e.glb",
      "girl-light": "/avatar/headz/girl/headwear-hat-pink-636f35b3.glb",
      "girl-medium": "/avatar/headz/girl/headwear-hat-pink-b032063f.glb"
     },
     "color": "#e7e7e7",
     "bytes": 22556,
     "tris": 5000,
     "rims": {
      "girl-dark": [
       0.612,
       -0.646
      ],
      "girl-light": [
       0.618,
       -0.463
      ],
      "girl-medium": [
       0.612,
       -0.647
      ]
     }
    }
   ],
   "earrings": []
  },
  "man": {
   "hair": [
    {
     "id": "001",
     "files": {
      "man-dark": "/avatar/headz/man/hair-001-1dae3147.glb",
      "man-light": "/avatar/headz/man/hair-001-a25eba93.glb",
      "man-medium": "/avatar/headz/man/hair-001-1dae3147.glb"
     },
     "color": "#141414",
     "bytes": 37208,
     "tris": 8000
    },
    {
     "id": "002",
     "files": {
      "man-dark": "/avatar/headz/man/hair-002-464d147e.glb",
      "man-light": "/avatar/headz/man/hair-002-302a9a06.glb",
      "man-medium": "/avatar/headz/man/hair-002-464d147e.glb"
     },
     "color": "#141414",
     "bytes": 37240,
     "tris": 7999
    },
    {
     "id": "003",
     "files": {
      "man-light": "/avatar/headz/man/hair-003-20c55769.glb"
     },
     "color": "#0a0504",
     "bytes": 34364,
     "tris": 7998
    },
    {
     "id": "003-001",
     "files": {
      "man-dark": "/avatar/headz/man/hair-003-001-45facd40.glb",
      "man-medium": "/avatar/headz/man/hair-003-001-45facd40.glb"
     },
     "color": "#141414",
     "bytes": 34264,
     "tris": 7998
    },
    {
     "id": "003-002",
     "files": {
      "man-dark": "/avatar/headz/man/hair-003-002-fd99c05a.glb",
      "man-medium": "/avatar/headz/man/hair-003-002-fd99c05a.glb"
     },
     "color": "#141414",
     "bytes": 24688,
     "tris": 5696
    },
    {
     "id": "004",
     "files": {
      "man-dark": "/avatar/headz/man/hair-004-d76ae262.glb",
      "man-light": "/avatar/headz/man/hair-004-08d2945d.glb",
      "man-medium": "/avatar/headz/man/hair-004-d76ae262.glb"
     },
     "color": "#141414",
     "bytes": 37312,
     "tris": 7999
    },
    {
     "id": "005",
     "files": {
      "man-dark": "/avatar/headz/man/hair-005-adc0c3a0.glb",
      "man-light": "/avatar/headz/man/hair-005-187cef26.glb",
      "man-medium": "/avatar/headz/man/hair-005-adc0c3a0.glb"
     },
     "color": "#141414",
     "bytes": 38692,
     "tris": 7998
    },
    {
     "id": "006",
     "files": {
      "man-dark": "/avatar/headz/man/hair-006-a65dd9e3.glb",
      "man-light": "/avatar/headz/man/hair-006-d18d13a8.glb",
      "man-medium": "/avatar/headz/man/hair-006-a65dd9e3.glb"
     },
     "color": "#141414",
     "bytes": 38228,
     "tris": 8000
    },
    {
     "id": "007",
     "files": {
      "man-dark": "/avatar/headz/man/hair-007-ee766cbc.glb",
      "man-light": "/avatar/headz/man/hair-007-cb31b473.glb",
      "man-medium": "/avatar/headz/man/hair-007-ee766cbc.glb"
     },
     "color": "#141414",
     "bytes": 32664,
     "tris": 8000
    },
    {
     "id": "008",
     "files": {
      "man-dark": "/avatar/headz/man/hair-008-274aac24.glb",
      "man-light": "/avatar/headz/man/hair-008-9a5b473c.glb",
      "man-medium": "/avatar/headz/man/hair-008-274aac24.glb"
     },
     "color": "#141414",
     "bytes": 38404,
     "tris": 8000
    },
    {
     "id": "009",
     "files": {
      "man-dark": "/avatar/headz/man/hair-009-738cb26c.glb",
      "man-light": "/avatar/headz/man/hair-009-7c897a67.glb",
      "man-medium": "/avatar/headz/man/hair-009-738cb26c.glb"
     },
     "color": "#141414",
     "bytes": 37380,
     "tris": 8000
    },
    {
     "id": "10",
     "files": {
      "man-dark": "/avatar/headz/man/hair-10-fb32623b.glb",
      "man-medium": "/avatar/headz/man/hair-10-fb32623b.glb"
     },
     "color": "#acacac",
     "bytes": 33872,
     "tris": 8000
    },
    {
     "id": "hair011",
     "files": {
      "man-dark": "/avatar/headz/man/hair-hair011-64202b85.glb",
      "man-light": "/avatar/headz/man/hair-hair011-7e792ffd.glb",
      "man-medium": "/avatar/headz/man/hair-hair011-64202b85.glb"
     },
     "color": "#191919",
     "bytes": 48996,
     "tris": 8000
    },
    {
     "id": "hair012",
     "files": {
      "man-light": "/avatar/headz/man/hair-hair012-f42293c1.glb"
     },
     "color": "#acacac",
     "bytes": 34284,
     "tris": 8000
    }
   ],
   "beard": [
    {
     "id": "beard01",
     "files": {
      "man-dark": "/avatar/headz/man/beard-beard01-f6188da3.glb",
      "man-light": "/avatar/headz/man/beard-beard01-0fcbf83f.glb",
      "man-medium": "/avatar/headz/man/beard-beard01-f6188da3.glb"
     },
     "color": "#191919",
     "bytes": 18760,
     "tris": 4144
    },
    {
     "id": "beard02",
     "files": {
      "man-dark": "/avatar/headz/man/beard-beard02-2f2600c9.glb",
      "man-light": "/avatar/headz/man/beard-beard02-67ebfef1.glb",
      "man-medium": "/avatar/headz/man/beard-beard02-2f2600c9.glb"
     },
     "color": "#000000",
     "bytes": 35284,
     "tris": 8000
    },
    {
     "id": "beard03",
     "files": {
      "man-light": "/avatar/headz/man/beard-beard03-752362a4.glb"
     },
     "color": "#2a2a2a",
     "bytes": 37192,
     "tris": 8000
    },
    {
     "id": "moustache-4",
     "files": {
      "man-dark": "/avatar/headz/man/beard-moustache-4-255107a5.glb",
      "man-medium": "/avatar/headz/man/beard-moustache-4-255107a5.glb"
     },
     "color": "#2a2a2a",
     "bytes": 36892,
     "tris": 8000
    },
    {
     "id": "moustache1",
     "files": {
      "man-light": "/avatar/headz/man/beard-moustache1-5756efb2.glb"
     },
     "color": "#191919",
     "bytes": 6496,
     "tris": 1088
    },
    {
     "id": "mustache-001",
     "files": {
      "man-dark": "/avatar/headz/man/beard-mustache-001-d95f7ce6.glb",
      "man-light": "/avatar/headz/man/beard-mustache-001-e56c6a52.glb",
      "man-medium": "/avatar/headz/man/beard-mustache-001-d95f7ce6.glb"
     },
     "color": "#141414",
     "bytes": 10304,
     "tris": 1664
    },
    {
     "id": "mustache-002",
     "files": {
      "man-dark": "/avatar/headz/man/beard-mustache-002-e260ffdf.glb",
      "man-light": "/avatar/headz/man/beard-mustache-002-e12eab0d.glb",
      "man-medium": "/avatar/headz/man/beard-mustache-002-e260ffdf.glb"
     },
     "color": "#141414",
     "bytes": 13120,
     "tris": 2432
    },
    {
     "id": "mustache-003",
     "files": {
      "man-dark": "/avatar/headz/man/beard-mustache-003-db36fae1.glb",
      "man-light": "/avatar/headz/man/beard-mustache-003-7a1290a7.glb",
      "man-medium": "/avatar/headz/man/beard-mustache-003-db36fae1.glb"
     },
     "color": "#141414",
     "bytes": 31448,
     "tris": 7488
    }
   ],
   "eyewear": [
    {
     "id": "glasses-001",
     "files": {
      "man-dark": "/avatar/headz/man/eyewear-glasses-001-4db45098.glb",
      "man-light": "/avatar/headz/man/eyewear-glasses-001-e4a71dd1.glb",
      "man-medium": "/avatar/headz/man/eyewear-glasses-001-4db45098.glb"
     },
     "color": "#000000",
     "bytes": 23516,
     "tris": 5000
    },
    {
     "id": "glasses-002",
     "files": {
      "man-dark": "/avatar/headz/man/eyewear-glasses-002-056c54a4.glb",
      "man-light": "/avatar/headz/man/eyewear-glasses-002-2a432aff.glb",
      "man-medium": "/avatar/headz/man/eyewear-glasses-002-056c54a4.glb"
     },
     "color": "#e7e1da",
     "bytes": 23572,
     "tris": 858
    },
    {
     "id": "glasses-003",
     "files": {
      "man-dark": "/avatar/headz/man/eyewear-glasses-003-e879ba3c.glb",
      "man-light": "/avatar/headz/man/eyewear-glasses-003-3f853512.glb",
      "man-medium": "/avatar/headz/man/eyewear-glasses-003-e879ba3c.glb"
     },
     "color": "#e7a300",
     "bytes": 22800,
     "tris": 836
    }
   ],
   "headwear": [
    {
     "id": "hat",
     "files": {
      "man-dark": "/avatar/headz/man/headwear-hat-d56b6733.glb",
      "man-light": "/avatar/headz/man/headwear-hat-4dbc1ee9.glb",
      "man-medium": "/avatar/headz/man/headwear-hat-d56b6733.glb"
     },
     "color": "#211d62",
     "bytes": 22160,
     "tris": 5000,
     "rims": {
      "man-dark": [
       0.509,
       0.122
      ],
      "man-light": [
       0.474,
       0.064
      ],
      "man-medium": [
       0.509,
       0.122
      ]
     }
    },
    {
     "id": "hat-2",
     "files": {
      "man-dark": "/avatar/headz/man/headwear-hat-2-1f95c3b7.glb",
      "man-medium": "/avatar/headz/man/headwear-hat-2-1f95c3b7.glb"
     },
     "color": "#e7e7e7",
     "bytes": 27624,
     "tris": 5000,
     "rims": {
      "man-dark": [
       0.327,
       0.202
      ],
      "man-medium": [
       0.327,
       0.202
      ]
     }
    }
   ],
   "earrings": []
  },
  "oldman": {
   "hair": [
    {
     "id": "1",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/hair-1-4975e669.glb",
      "oldman-light": "/avatar/headz/oldman/hair-1-36cb9e2a.glb",
      "oldman-medium": "/avatar/headz/oldman/hair-1-5158d379.glb"
     },
     "color": "#aebeb2",
     "bytes": 34876,
     "tris": 7998
    },
    {
     "id": "2",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/hair-2-183d9bd0.glb",
      "oldman-light": "/avatar/headz/oldman/hair-2-0e199b24.glb",
      "oldman-medium": "/avatar/headz/oldman/hair-2-e6a9f070.glb"
     },
     "color": "#aebeb2",
     "bytes": 35568,
     "tris": 8000
    },
    {
     "id": "3",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/hair-3-07a40e40.glb",
      "oldman-light": "/avatar/headz/oldman/hair-3-d3e5df7a.glb",
      "oldman-medium": "/avatar/headz/oldman/hair-3-b665f994.glb"
     },
     "color": "#aebeb2",
     "bytes": 34724,
     "tris": 7998
    },
    {
     "id": "4",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/hair-4-e838d146.glb",
      "oldman-light": "/avatar/headz/oldman/hair-4-007a2a07.glb",
      "oldman-medium": "/avatar/headz/oldman/hair-4-8c131a4b.glb"
     },
     "color": "#aebeb2",
     "bytes": 35808,
     "tris": 7998
    },
    {
     "id": "5",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/hair-5-362f29d3.glb",
      "oldman-light": "/avatar/headz/oldman/hair-5-7a55ce57.glb",
      "oldman-medium": "/avatar/headz/oldman/hair-5-d1bf31a1.glb"
     },
     "color": "#aebeb2",
     "bytes": 35444,
     "tris": 7998
    },
    {
     "id": "6",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/hair-6-36a75806.glb",
      "oldman-light": "/avatar/headz/oldman/hair-6-0bf0cc88.glb",
      "oldman-medium": "/avatar/headz/oldman/hair-6-ad9c32e5.glb"
     },
     "color": "#aebeb2",
     "bytes": 36224,
     "tris": 7998
    },
    {
     "id": "7",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/hair-7-70b30c2e.glb",
      "oldman-light": "/avatar/headz/oldman/hair-7-5723d946.glb",
      "oldman-medium": "/avatar/headz/oldman/hair-7-3389871b.glb"
     },
     "color": "#aebeb2",
     "bytes": 36200,
     "tris": 7998
    },
    {
     "id": "8",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/hair-8-bc77d66b.glb",
      "oldman-light": "/avatar/headz/oldman/hair-8-edce607a.glb",
      "oldman-medium": "/avatar/headz/oldman/hair-8-e8e116c1.glb"
     },
     "color": "#aebeb2",
     "bytes": 34260,
     "tris": 7998
    }
   ],
   "beard": [
    {
     "id": "beard",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/beard-beard-d4a0ad5f.glb",
      "oldman-light": "/avatar/headz/oldman/beard-beard-23661ba0.glb",
      "oldman-medium": "/avatar/headz/oldman/beard-beard-5bf24d11.glb"
     },
     "color": "#aebeb2",
     "bytes": 35984,
     "tris": 8000
    },
    {
     "id": "mustache",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/beard-mustache-3a46ea05.glb",
      "oldman-light": "/avatar/headz/oldman/beard-mustache-d3e3c128.glb",
      "oldman-medium": "/avatar/headz/oldman/beard-mustache-cf3d81c3.glb"
     },
     "color": "#aebeb2",
     "bytes": 33224,
     "tris": 2048
    }
   ],
   "eyewear": [
    {
     "id": "glasses-black",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/eyewear-glasses-black-7057536f.glb",
      "oldman-light": "/avatar/headz/oldman/eyewear-glasses-black-0f42c642.glb",
      "oldman-medium": "/avatar/headz/oldman/eyewear-glasses-black-27ce9b17.glb"
     },
     "color": "#10100f",
     "bytes": 23376,
     "tris": 5000
    },
    {
     "id": "glasses-black-small",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/eyewear-glasses-black-small-eebd2684.glb",
      "oldman-light": "/avatar/headz/oldman/eyewear-glasses-black-small-daaafcc0.glb",
      "oldman-medium": "/avatar/headz/oldman/eyewear-glasses-black-small-4fd1bf14.glb"
     },
     "color": "#292929",
     "bytes": 24868,
     "tris": 5000
    },
    {
     "id": "glasses-white",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/eyewear-glasses-white-ef2d1625.glb",
      "oldman-light": "/avatar/headz/oldman/eyewear-glasses-white-a2c6057e.glb",
      "oldman-medium": "/avatar/headz/oldman/eyewear-glasses-white-73837b97.glb"
     },
     "color": "#e7e1da",
     "bytes": 22468,
     "tris": 5000
    },
    {
     "id": "glasses-yellow",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/eyewear-glasses-yellow-97b13ecd.glb",
      "oldman-light": "/avatar/headz/oldman/eyewear-glasses-yellow-06d20d63.glb",
      "oldman-medium": "/avatar/headz/oldman/eyewear-glasses-yellow-60a9b5ba.glb"
     },
     "color": "#e7ae62",
     "bytes": 25176,
     "tris": 5000
    }
   ],
   "headwear": [
    {
     "id": "beanie-red",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/headwear-beanie-red-3a5c62c0.glb",
      "oldman-light": "/avatar/headz/oldman/headwear-beanie-red-45819bc9.glb",
      "oldman-medium": "/avatar/headz/oldman/headwear-beanie-red-6ce9c49d.glb"
     },
     "color": "#9d2c1d",
     "bytes": 26640,
     "tris": 5000,
     "rims": {
      "oldman-dark": [
       0.463,
       0.047
      ],
      "oldman-light": [
       0.508,
       -0.031
      ],
      "oldman-medium": [
       0.471,
       0.049
      ]
     }
    },
    {
     "id": "cap-green-white",
     "files": {
      "oldman-light": "/avatar/headz/oldman/headwear-cap-green-white-d21c5110.glb"
     },
     "color": "#85c8ac",
     "bytes": 25296,
     "tris": 5000,
     "rims": {
      "oldman-light": [
       0.36,
       0.433
      ]
     }
    },
    {
     "id": "cap-grey",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/headwear-cap-grey-e29d0353.glb",
      "oldman-light": "/avatar/headz/oldman/headwear-cap-grey-b9d6be32.glb",
      "oldman-medium": "/avatar/headz/oldman/headwear-cap-grey-122cf504.glb"
     },
     "color": "#626262",
     "bytes": 25072,
     "tris": 5000,
     "rims": {
      "oldman-dark": [
       0.299,
       -0.057
      ],
      "oldman-light": [
       0.414,
       -0.014
      ],
      "oldman-medium": [
       0.303,
       -0.055
      ]
     }
    },
    {
     "id": "hat-black",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/headwear-hat-black-bd96a51d.glb",
      "oldman-light": "/avatar/headz/oldman/headwear-hat-black-b08305a3.glb",
      "oldman-medium": "/avatar/headz/oldman/headwear-hat-black-47b84bec.glb"
     },
     "color": "#060606",
     "bytes": 26524,
     "tris": 5000,
     "rims": {
      "oldman-dark": [
       0.255,
       0.394
      ],
      "oldman-light": [
       0.294,
       0.489
      ],
      "oldman-medium": [
       0.257,
       0.395
      ]
     }
    },
    {
     "id": "hat-white",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/headwear-hat-white-2a7d98bf.glb",
      "oldman-light": "/avatar/headz/oldman/headwear-hat-white-66f25eaf.glb",
      "oldman-medium": "/avatar/headz/oldman/headwear-hat-white-aa53b75d.glb"
     },
     "color": "#f7f0f1",
     "bytes": 26340,
     "tris": 5000,
     "rims": {
      "oldman-dark": [
       0.162,
       -0.005
      ],
      "oldman-light": [
       0.259,
       0.231
      ],
      "oldman-medium": [
       0.164,
       -0.002
      ]
     }
    },
    {
     "id": "hat-yellow",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/headwear-hat-yellow-1d3ac020.glb",
      "oldman-light": "/avatar/headz/oldman/headwear-hat-yellow-4aa89dbf.glb",
      "oldman-medium": "/avatar/headz/oldman/headwear-hat-yellow-357f2834.glb"
     },
     "color": "#e7b16c",
     "bytes": 27400,
     "tris": 5000,
     "rims": {
      "oldman-dark": [
       0.528,
       -0.117
      ],
      "oldman-light": [
       0.694,
       -0.067
      ],
      "oldman-medium": [
       0.529,
       -0.115
      ]
     }
    }
   ],
   "earrings": []
  },
  "oldwoman": {
   "hair": [
    {
     "id": "1",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-1-d6a9e336.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-1-eb87e580.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-1-a29cabd1.glb"
     },
     "color": "#aebeb2",
     "bytes": 34040,
     "tris": 7998
    },
    {
     "id": "2",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-2-fd62880c.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-2-f9b9a176.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-2-c022a433.glb"
     },
     "color": "#aebeb2",
     "bytes": 35428,
     "tris": 7998
    },
    {
     "id": "3",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-3-89305ed0.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-3-0350c917.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-3-a7ed805f.glb"
     },
     "color": "#aebeb2",
     "bytes": 39568,
     "tris": 7999
    },
    {
     "id": "4",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-4-813b17fb.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-4-34260f3e.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-4-cf743d76.glb"
     },
     "color": "#aebeb2",
     "bytes": 38916,
     "tris": 7999
    },
    {
     "id": "5",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-5-868d8293.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-5-f0317a7d.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-5-caa4ae75.glb"
     },
     "color": "#aebeb2",
     "bytes": 37128,
     "tris": 8000
    },
    {
     "id": "6",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-6-ad49efa5.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-6-44b3aabf.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-6-3c1970d5.glb"
     },
     "color": "#aebeb2",
     "bytes": 38184,
     "tris": 7998
    },
    {
     "id": "7",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-7-904f60e6.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-7-68b7f115.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-7-3f637caa.glb"
     },
     "color": "#aebeb2",
     "bytes": 35540,
     "tris": 8000
    },
    {
     "id": "8",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-8-72eaf88f.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-8-b44e557e.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-8-264686fe.glb"
     },
     "color": "#aebeb2",
     "bytes": 38856,
     "tris": 8000
    },
    {
     "id": "9",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-9-70b91552.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-9-94cbd53d.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-9-96f6f983.glb"
     },
     "color": "#aebeb2",
     "bytes": 36892,
     "tris": 8000
    },
    {
     "id": "10",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-10-a0001322.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-10-c26131d3.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-10-3a224eb8.glb"
     },
     "color": "#aebeb2",
     "bytes": 37504,
     "tris": 8000
    },
    {
     "id": "11",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-11-52e3b0e3.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-11-fa6f935f.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-11-38dc687e.glb"
     },
     "color": "#aebeb2",
     "bytes": 37056,
     "tris": 8000
    }
   ],
   "beard": [],
   "eyewear": [
    {
     "id": "glasses-black",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/eyewear-glasses-black-5f9856e8.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/eyewear-glasses-black-fa9d7392.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/eyewear-glasses-black-18196b47.glb"
     },
     "color": "#10100f",
     "bytes": 23208,
     "tris": 5000
    },
    {
     "id": "glasses-black-small",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/eyewear-glasses-black-small-3b7a4899.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/eyewear-glasses-black-small-9e0ffe04.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/eyewear-glasses-black-small-46e61379.glb"
     },
     "color": "#292929",
     "bytes": 24716,
     "tris": 5000
    },
    {
     "id": "glasses-red",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/eyewear-glasses-red-e7a5187c.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/eyewear-glasses-red-73c5235c.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/eyewear-glasses-red-d9806354.glb"
     },
     "color": "#a11100",
     "bytes": 22696,
     "tris": 5000
    },
    {
     "id": "glasses-white",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/eyewear-glasses-white-aef9a790.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/eyewear-glasses-white-1194187b.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/eyewear-glasses-white-88930441.glb"
     },
     "color": "#e7e1da",
     "bytes": 22636,
     "tris": 5000
    },
    {
     "id": "glasses-yellow",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/eyewear-glasses-yellow-50d673c0.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/eyewear-glasses-yellow-651980a7.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/eyewear-glasses-yellow-e5fa7006.glb"
     },
     "color": "#e7ae62",
     "bytes": 25468,
     "tris": 5000
    }
   ],
   "headwear": [
    {
     "id": "beanie-red",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/headwear-beanie-red-926a6d98.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/headwear-beanie-red-d947d4af.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/headwear-beanie-red-8b26d170.glb"
     },
     "color": "#9d2c1d",
     "bytes": 27284,
     "tris": 5000,
     "rims": {
      "oldwoman-dark": [
       0.485,
       -0.116
      ],
      "oldwoman-light": [
       0.386,
       -0.188
      ],
      "oldwoman-medium": [
       0.481,
       -0.125
      ]
     }
    },
    {
     "id": "cap-grey",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/headwear-cap-grey-39036259.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/headwear-cap-grey-7901eccd.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/headwear-cap-grey-91551a00.glb"
     },
     "color": "#626262",
     "bytes": 24812,
     "tris": 5000,
     "rims": {
      "oldwoman-dark": [
       0.353,
       -0.069
      ],
      "oldwoman-light": [
       0.33,
       -0.045
      ],
      "oldwoman-medium": [
       0.348,
       -0.078
      ]
     }
    },
    {
     "id": "hat-grey",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/headwear-hat-grey-17255487.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/headwear-hat-grey-5461302c.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/headwear-hat-grey-2edd45dd.glb"
     },
     "color": "#504e4f",
     "bytes": 24568,
     "tris": 5000,
     "rims": {
      "oldwoman-dark": [
       0.52,
       -0.383
      ],
      "oldwoman-light": [
       0.609,
       -0.331
      ],
      "oldwoman-medium": [
       0.516,
       -0.395
      ]
     }
    },
    {
     "id": "hat-yellow",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/headwear-hat-yellow-14b96924.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/headwear-hat-yellow-83aa0e06.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/headwear-hat-yellow-53919561.glb"
     },
     "color": "#e7b16c",
     "bytes": 27052,
     "tris": 5000,
     "rims": {
      "oldwoman-dark": [
       0.685,
       -0.142
      ],
      "oldwoman-light": [
       0.628,
       -0.387
      ],
      "oldwoman-medium": [
       0.682,
       -0.152
      ]
     }
    }
   ],
   "earrings": []
  },
  "woman": {
   "hair": [
    {
     "id": "001",
     "files": {
      "woman-dark": "/avatar/headz/woman/hair-001-222be474.glb",
      "woman-light": "/avatar/headz/woman/hair-001-b8f746f9.glb",
      "woman-medium": "/avatar/headz/woman/hair-001-222be474.glb"
     },
     "color": "#140505",
     "bytes": 34892,
     "tris": 7999
    },
    {
     "id": "002",
     "files": {
      "woman-dark": "/avatar/headz/woman/hair-002-53e2ab4b.glb",
      "woman-light": "/avatar/headz/woman/hair-002-2c437895.glb",
      "woman-medium": "/avatar/headz/woman/hair-002-53e2ab4b.glb"
     },
     "color": "#140505",
     "bytes": 36108,
     "tris": 8000
    },
    {
     "id": "003",
     "files": {
      "woman-dark": "/avatar/headz/woman/hair-003-4a2e6ab2.glb",
      "woman-light": "/avatar/headz/woman/hair-003-a5e8b06f.glb",
      "woman-medium": "/avatar/headz/woman/hair-003-4a2e6ab2.glb"
     },
     "color": "#140505",
     "bytes": 36352,
     "tris": 8000
    },
    {
     "id": "004",
     "files": {
      "woman-dark": "/avatar/headz/woman/hair-004-c09ed267.glb",
      "woman-light": "/avatar/headz/woman/hair-004-32df56e0.glb",
      "woman-medium": "/avatar/headz/woman/hair-004-c09ed267.glb"
     },
     "color": "#140505",
     "bytes": 37516,
     "tris": 8000
    },
    {
     "id": "005",
     "files": {
      "woman-dark": "/avatar/headz/woman/hair-005-57c39ea5.glb",
      "woman-light": "/avatar/headz/woman/hair-005-d83921d9.glb",
      "woman-medium": "/avatar/headz/woman/hair-005-57c39ea5.glb"
     },
     "color": "#140505",
     "bytes": 34948,
     "tris": 7999
    },
    {
     "id": "006",
     "files": {
      "woman-dark": "/avatar/headz/woman/hair-006-d5784fd4.glb",
      "woman-light": "/avatar/headz/woman/hair-006-a6d6a56c.glb",
      "woman-medium": "/avatar/headz/woman/hair-006-d5784fd4.glb"
     },
     "color": "#140505",
     "bytes": 36152,
     "tris": 8000
    },
    {
     "id": "007",
     "files": {
      "woman-dark": "/avatar/headz/woman/hair-007-8ff145b8.glb",
      "woman-light": "/avatar/headz/woman/hair-007-5a395f7f.glb",
      "woman-medium": "/avatar/headz/woman/hair-007-8ff145b8.glb"
     },
     "color": "#140505",
     "bytes": 38080,
     "tris": 7999
    },
    {
     "id": "008",
     "files": {
      "woman-dark": "/avatar/headz/woman/hair-008-433581e0.glb",
      "woman-light": "/avatar/headz/woman/hair-008-90d9de7d.glb",
      "woman-medium": "/avatar/headz/woman/hair-008-433581e0.glb"
     },
     "color": "#140505",
     "bytes": 36520,
     "tris": 8000
    },
    {
     "id": "009",
     "files": {
      "woman-dark": "/avatar/headz/woman/hair-009-f47364ed.glb",
      "woman-light": "/avatar/headz/woman/hair-009-c7d17eb6.glb",
      "woman-medium": "/avatar/headz/woman/hair-009-f47364ed.glb"
     },
     "color": "#140505",
     "bytes": 38364,
     "tris": 8000
    },
    {
     "id": "010",
     "files": {
      "woman-dark": "/avatar/headz/woman/hair-010-66d95eda.glb",
      "woman-light": "/avatar/headz/woman/hair-010-be0e0e6f.glb",
      "woman-medium": "/avatar/headz/woman/hair-010-66d95eda.glb"
     },
     "color": "#140505",
     "bytes": 33168,
     "tris": 7808
    }
   ],
   "beard": [],
   "eyewear": [
    {
     "id": "glasses-001",
     "files": {
      "woman-dark": "/avatar/headz/woman/eyewear-glasses-001-0576f238.glb",
      "woman-light": "/avatar/headz/woman/eyewear-glasses-001-fab41bec.glb",
      "woman-medium": "/avatar/headz/woman/eyewear-glasses-001-0576f238.glb"
     },
     "color": "#e7e7e7",
     "bytes": 23400,
     "tris": 5000
    },
    {
     "id": "glasses-002",
     "files": {
      "woman-dark": "/avatar/headz/woman/eyewear-glasses-002-82ebb390.glb",
      "woman-light": "/avatar/headz/woman/eyewear-glasses-002-f556e1c4.glb",
      "woman-medium": "/avatar/headz/woman/eyewear-glasses-002-82ebb390.glb"
     },
     "color": "#e7e7e7",
     "bytes": 23768,
     "tris": 5000
    },
    {
     "id": "glasses-003",
     "files": {
      "woman-dark": "/avatar/headz/woman/eyewear-glasses-003-4d7df4ab.glb",
      "woman-light": "/avatar/headz/woman/eyewear-glasses-003-9930e80c.glb",
      "woman-medium": "/avatar/headz/woman/eyewear-glasses-003-4d7df4ab.glb"
     },
     "color": "#161616",
     "bytes": 22584,
     "tris": 5000
    }
   ],
   "headwear": [
    {
     "id": "hat",
     "files": {
      "woman-dark": "/avatar/headz/woman/headwear-hat-72a6110c.glb",
      "woman-light": "/avatar/headz/woman/headwear-hat-d30179fc.glb",
      "woman-medium": "/avatar/headz/woman/headwear-hat-72a6110c.glb"
     },
     "color": "#e7e7e7",
     "bytes": 24404,
     "tris": 4999,
     "rims": {
      "woman-dark": [
       0.757,
       -0.697
      ],
      "woman-light": [
       0.731,
       -0.589
      ],
      "woman-medium": [
       0.757,
       -0.697
      ]
     }
    }
   ],
   "earrings": [
    {
     "id": "earrings",
     "files": {
      "woman-dark": "/avatar/headz/woman/earrings-earrings-6d47d753.glb",
      "woman-light": "/avatar/headz/woman/earrings-earrings-b0ce4549.glb",
      "woman-medium": "/avatar/headz/woman/earrings-earrings-6d47d753.glb"
     },
     "color": "#e7d5a5",
     "bytes": 21604,
     "tris": 5000
    }
   ]
  }
 }
};
