/* eslint-disable */
// Generated by tools/headz/build.mjs — do not edit.
import type { HeadzCatalog } from "./types";

export const CATALOG: HeadzCatalog = {
 "version": "3a7e1e1618",
 "bases": [
  {
   "id": "woman-light",
   "group": "woman",
   "tone": "light",
   "face": "/avatar/headz/woman-light/face.glb",
   "lod": "/avatar/headz/woman-light/face-lod.glb",
   "bytes": 477852,
   "tris": 21368,
   "skin": "#e18d72",
   "hair": "#efb974",
   "iris": "#015d74",
   "defaults": {
    "hair": "005"
   },
   "fit": "/avatar/headz/woman-light/fit.bin",
   "eyes": {
    "L": {
     "c": [
      0.2954,
      -0.0725,
      0.4795
     ],
     "r": 0.1857,
     "axis": [
      0,
      0.0035,
      1
     ],
     "iris": 46.5,
     "pupil": 27.3
    },
    "R": {
     "c": [
      -0.2997,
      -0.0715,
      0.4762
     ],
     "r": 0.1857,
     "axis": [
      0,
      0.0038,
      1
     ],
     "iris": 46.5,
     "pupil": 27.3
    }
   },
   "lm": {
    "nose": [
     0,
     -0.3789,
     0.878
    ],
    "mouthL": [
     0.2379,
     -0.6406,
     0.5992
    ],
    "mouthR": [
     -0.2379,
     -0.6406,
     0.5992
    ],
    "chin": [
     0,
     -1,
     0.5033
    ],
    "crown": 1,
    "bottom": -1,
    "temple": 0.7,
    "jaw": 0.5664,
    "ear": 0.87
   }
  },
  {
   "id": "woman-medium",
   "group": "woman",
   "tone": "medium",
   "face": "/avatar/headz/woman-medium/face.glb",
   "lod": "/avatar/headz/woman-medium/face-lod.glb",
   "bytes": 527172,
   "tris": 22085,
   "skin": "#a96248",
   "hair": "#140505",
   "iris": "#3f3027",
   "defaults": {
    "hair": "010"
   },
   "fit": "/avatar/headz/woman-medium/fit.bin",
   "eyes": {
    "L": {
     "c": [
      0.306,
      -0.1226,
      0.4443
     ],
     "r": 0.1838,
     "axis": [
      0.0451,
      -0.0136,
      0.9989
     ],
     "iris": 33.8,
     "pupil": 14.2
    },
    "R": {
     "c": [
      -0.306,
      -0.1226,
      0.4443
     ],
     "r": 0.1838,
     "axis": [
      -0.0451,
      -0.0136,
      0.9989
     ],
     "iris": 33.8,
     "pupil": 14.2
    }
   },
   "lm": {
    "nose": [
     0,
     -0.4311,
     0.8983
    ],
    "mouthL": [
     0.312,
     -0.6347,
     0.5084
    ],
    "mouthR": [
     -0.312,
     -0.6347,
     0.5084
    ],
    "chin": [
     0,
     -1,
     0.5211
    ],
    "crown": 1,
    "bottom": -1,
    "temple": 0.7249,
    "jaw": 0.6052,
    "ear": 0.9021
   }
  },
  {
   "id": "woman-dark",
   "group": "woman",
   "tone": "dark",
   "face": "/avatar/headz/woman-dark/face.glb",
   "lod": "/avatar/headz/woman-dark/face-lod.glb",
   "bytes": 527156,
   "tris": 22085,
   "skin": "#743928",
   "hair": "#140505",
   "iris": "#3f3027",
   "defaults": {
    "hair": "010"
   },
   "fit": "/avatar/headz/woman-dark/fit.bin",
   "eyes": {
    "L": {
     "c": [
      0.306,
      -0.1226,
      0.4443
     ],
     "r": 0.1838,
     "axis": [
      0.0451,
      -0.0136,
      0.9989
     ],
     "iris": 33.8,
     "pupil": 14.2
    },
    "R": {
     "c": [
      -0.306,
      -0.1226,
      0.4443
     ],
     "r": 0.1838,
     "axis": [
      -0.0451,
      -0.0136,
      0.9989
     ],
     "iris": 33.8,
     "pupil": 14.2
    }
   },
   "lm": {
    "nose": [
     0,
     -0.4311,
     0.8983
    ],
    "mouthL": [
     0.312,
     -0.6347,
     0.5084
    ],
    "mouthR": [
     -0.312,
     -0.6347,
     0.5084
    ],
    "chin": [
     0,
     -1,
     0.5211
    ],
    "crown": 1,
    "bottom": -1,
    "temple": 0.7249,
    "jaw": 0.6052,
    "ear": 0.9021
   }
  },
  {
   "id": "man-light",
   "group": "man",
   "tone": "light",
   "face": "/avatar/headz/man-light/face.glb",
   "lod": "/avatar/headz/man-light/face-lod.glb",
   "bytes": 499992,
   "tris": 22168,
   "skin": "#ba6956",
   "hair": "#0a0504",
   "iris": "#2c1005",
   "defaults": {
    "hair": "001"
   },
   "fit": "/avatar/headz/man-light/fit.bin",
   "eyes": {
    "L": {
     "c": [
      0.2867,
      -0.0819,
      0.3808
     ],
     "r": 0.188,
     "axis": [
      0,
      0,
      1
     ],
     "iris": 33.5,
     "pupil": 15.2
    },
    "R": {
     "c": [
      -0.2919,
      -0.081,
      0.3816
     ],
     "r": 0.188,
     "axis": [
      0,
      0,
      1
     ],
     "iris": 33.5,
     "pupil": 15.2
    }
   },
   "lm": {
    "nose": [
     0,
     -0.4246,
     0.8878
    ],
    "mouthL": [
     0.2382,
     -0.643,
     0.5959
    ],
    "mouthR": [
     -0.2382,
     -0.643,
     0.5959
    ],
    "chin": [
     0,
     -1,
     0.4593
    ],
    "crown": 1,
    "bottom": -1,
    "temple": 0.6877,
    "jaw": 0.5287,
    "ear": 0.9044
   }
  },
  {
   "id": "man-medium",
   "group": "man",
   "tone": "medium",
   "face": "/avatar/headz/man-medium/face.glb",
   "lod": "/avatar/headz/man-medium/face-lod.glb",
   "bytes": 542196,
   "tris": 21048,
   "skin": "#ae674f",
   "hair": "#141414",
   "iris": "#070201",
   "defaults": {
    "beard": "moustache-4",
    "hair": "001"
   },
   "fit": "/avatar/headz/man-medium/fit.bin",
   "eyes": {
    "L": {
     "c": [
      0.3147,
      0.028,
      0.3751
     ],
     "r": 0.19,
     "axis": [
      0,
      0,
      1
     ],
     "iris": 33.9,
     "pupil": 15.3
    },
    "R": {
     "c": [
      -0.3145,
      0.028,
      0.3751
     ],
     "r": 0.19,
     "axis": [
      0,
      0,
      1
     ],
     "iris": 33.9,
     "pupil": 15.3
    }
   },
   "lm": {
    "nose": [
     0.0029,
     -0.3256,
     0.8503
    ],
    "mouthL": [
     0.3095,
     -0.6109,
     0.4812
    ],
    "mouthR": [
     -0.3013,
     -0.6112,
     0.4791
    ],
    "chin": [
     0.0029,
     -1,
     0.4354
    ],
    "crown": 1,
    "bottom": -1,
    "temple": 0.9005,
    "jaw": 0.587
   }
  },
  {
   "id": "man-dark",
   "group": "man",
   "tone": "dark",
   "face": "/avatar/headz/man-dark/face.glb",
   "lod": "/avatar/headz/man-dark/face-lod.glb",
   "bytes": 542196,
   "tris": 21048,
   "skin": "#68382a",
   "hair": "#141414",
   "iris": "#070201",
   "defaults": {
    "beard": "moustache-4",
    "hair": "001"
   },
   "fit": "/avatar/headz/man-dark/fit.bin",
   "eyes": {
    "L": {
     "c": [
      0.3147,
      0.028,
      0.3751
     ],
     "r": 0.19,
     "axis": [
      0,
      0,
      1
     ],
     "iris": 33.9,
     "pupil": 15.3
    },
    "R": {
     "c": [
      -0.3145,
      0.028,
      0.3751
     ],
     "r": 0.19,
     "axis": [
      0,
      0,
      1
     ],
     "iris": 33.9,
     "pupil": 15.3
    }
   },
   "lm": {
    "nose": [
     0.0029,
     -0.3256,
     0.8503
    ],
    "mouthL": [
     0.3095,
     -0.6109,
     0.4812
    ],
    "mouthR": [
     -0.3013,
     -0.6112,
     0.4791
    ],
    "chin": [
     0.0029,
     -1,
     0.4354
    ],
    "crown": 1,
    "bottom": -1,
    "temple": 0.9005,
    "jaw": 0.587
   }
  },
  {
   "id": "girl-light",
   "group": "girl",
   "tone": "light",
   "face": "/avatar/headz/girl-light/face.glb",
   "lod": "/avatar/headz/girl-light/face-lod.glb",
   "bytes": 754596,
   "tris": 19960,
   "skin": "#f2c6ba",
   "hair": "#260e0d",
   "iris": "#a4c1b9",
   "defaults": {
    "hair": "1"
   },
   "fit": "/avatar/headz/girl-light/fit.bin",
   "eyes": {
    "L": {
     "c": [
      0.3132,
      -0.0828,
      0.3636
     ],
     "r": 0.2986,
     "axis": [
      0.1619,
      -0.0799,
      0.9836
     ],
     "iris": 24.6,
     "pupil": 10.3
    },
    "R": {
     "c": [
      -0.3132,
      -0.0828,
      0.3636
     ],
     "r": 0.2986,
     "axis": [
      -0.1619,
      -0.0799,
      0.9836
     ],
     "iris": 24.6,
     "pupil": 10.3
    }
   },
   "lm": {
    "nose": [
     0,
     -0.415,
     0.9168
    ],
    "mouthL": [
     0.2656,
     -0.6304,
     0.6607
    ],
    "mouthR": [
     -0.2656,
     -0.6304,
     0.6607
    ],
    "chin": [
     0,
     -1,
     0.5522
    ],
    "crown": 1,
    "bottom": -1,
    "temple": 0.9264,
    "jaw": 0.6724
   }
  },
  {
   "id": "girl-medium",
   "group": "girl",
   "tone": "medium",
   "face": "/avatar/headz/girl-medium/face.glb",
   "lod": "/avatar/headz/girl-medium/face-lod.glb",
   "bytes": 969528,
   "tris": 19280,
   "skin": "#ab8a7b",
   "hair": "#260e0d",
   "iris": "#c0a19a",
   "defaults": {
    "hair": "3"
   },
   "fit": "/avatar/headz/girl-medium/fit.bin",
   "eyes": {
    "L": {
     "c": [
      0.3683,
      -0.1599,
      0.4882
     ],
     "r": 0.2158,
     "axis": [
      0.047,
      -0.0239,
      0.9986
     ],
     "iris": 22.5,
     "pupil": 9.5
    },
    "R": {
     "c": [
      -0.3683,
      -0.1599,
      0.4882
     ],
     "r": 0.2158,
     "axis": [
      -0.047,
      -0.0239,
      0.9986
     ],
     "iris": 22.5,
     "pupil": 9.5
    }
   },
   "lm": {
    "nose": [
     0,
     -0.4225,
     0.9594
    ],
    "mouthL": [
     0.1723,
     -0.6254,
     0.7772
    ],
    "mouthR": [
     -0.1723,
     -0.6254,
     0.7772
    ],
    "chin": [
     0,
     -1,
     0.5611
    ],
    "crown": 1,
    "bottom": -1,
    "temple": 0.9476,
    "jaw": 0.6468
   }
  },
  {
   "id": "girl-dark",
   "group": "girl",
   "tone": "dark",
   "face": "/avatar/headz/girl-dark/face.glb",
   "lod": "/avatar/headz/girl-dark/face-lod.glb",
   "bytes": 964600,
   "tris": 19280,
   "skin": "#6e4330",
   "hair": "#72351c",
   "iris": "#c0a19a",
   "defaults": {
    "hair": "3"
   },
   "fit": "/avatar/headz/girl-dark/fit.bin",
   "eyes": {
    "L": {
     "c": [
      0.3682,
      -0.1595,
      0.487
     ],
     "r": 0.2157,
     "axis": [
      0.047,
      -0.0239,
      0.9986
     ],
     "iris": 22.5,
     "pupil": 9.5
    },
    "R": {
     "c": [
      -0.3682,
      -0.1595,
      0.487
     ],
     "r": 0.2157,
     "axis": [
      -0.047,
      -0.0239,
      0.9986
     ],
     "iris": 22.5,
     "pupil": 9.5
    }
   },
   "lm": {
    "nose": [
     0,
     -0.4082,
     0.9602
    ],
    "mouthL": [
     0.1918,
     -0.6182,
     0.7765
    ],
    "mouthR": [
     -0.1918,
     -0.6182,
     0.7765
    ],
    "chin": [
     0,
     -1,
     0.5588
    ],
    "crown": 1,
    "bottom": -1,
    "temple": 0.9474,
    "jaw": 0.6637
   }
  },
  {
   "id": "boy-light",
   "group": "boy",
   "tone": "light",
   "face": "/avatar/headz/boy-light/face.glb",
   "lod": "/avatar/headz/boy-light/face-lod.glb",
   "bytes": 931968,
   "tris": 25108,
   "skin": "#f0c5b2",
   "hair": "#dba769",
   "iris": "#bc938a",
   "defaults": {
    "hair": "5"
   },
   "fit": "/avatar/headz/boy-light/fit.bin",
   "eyes": {
    "L": {
     "c": [
      0.2752,
      -0.1169,
      0.4573
     ],
     "r": 0.2529,
     "axis": [
      0.1457,
      -0.0004,
      0.9893
     ],
     "iris": 22.5,
     "pupil": 9.5
    },
    "R": {
     "c": [
      -0.2752,
      -0.1169,
      0.4573
     ],
     "r": 0.2529,
     "axis": [
      -0.1457,
      -0.0004,
      0.9893
     ],
     "iris": 22.5,
     "pupil": 9.5
    }
   },
   "lm": {
    "nose": [
     0,
     -0.399,
     0.9508
    ],
    "mouthL": [
     0.2621,
     -0.5988,
     0.6793
    ],
    "mouthR": [
     -0.2621,
     -0.5988,
     0.6793
    ],
    "chin": [
     0,
     -1,
     0.5623
    ],
    "crown": 1,
    "bottom": -1,
    "temple": 0.8957,
    "jaw": 0.5886
   }
  },
  {
   "id": "boy-medium",
   "group": "boy",
   "tone": "medium",
   "face": "/avatar/headz/boy-medium/face.glb",
   "lod": "/avatar/headz/boy-medium/face-lod.glb",
   "bytes": 843292,
   "tris": 25108,
   "skin": "#b07550",
   "hair": "#260e0d",
   "iris": "#bc938a",
   "defaults": {
    "hair": "6"
   },
   "fit": "/avatar/headz/boy-medium/fit.bin",
   "eyes": {
    "L": {
     "c": [
      0.2752,
      -0.1169,
      0.4573
     ],
     "r": 0.2529,
     "axis": [
      0.1457,
      -0.0004,
      0.9893
     ],
     "iris": 22.5,
     "pupil": 9.5
    },
    "R": {
     "c": [
      -0.2752,
      -0.1169,
      0.4573
     ],
     "r": 0.2529,
     "axis": [
      -0.1457,
      -0.0004,
      0.9893
     ],
     "iris": 22.5,
     "pupil": 9.5
    }
   },
   "lm": {
    "nose": [
     0,
     -0.399,
     0.9508
    ],
    "mouthL": [
     0.2621,
     -0.5988,
     0.6793
    ],
    "mouthR": [
     -0.2621,
     -0.5988,
     0.6793
    ],
    "chin": [
     0,
     -1,
     0.5623
    ],
    "crown": 1,
    "bottom": -1,
    "temple": 0.8957,
    "jaw": 0.5886
   }
  },
  {
   "id": "boy-dark",
   "group": "boy",
   "tone": "dark",
   "face": "/avatar/headz/boy-dark/face.glb",
   "lod": "/avatar/headz/boy-dark/face-lod.glb",
   "bytes": 843284,
   "tris": 25108,
   "skin": "#6e4330",
   "hair": "#72351c",
   "iris": "#bc938a",
   "defaults": {
    "hair": "2"
   },
   "fit": "/avatar/headz/boy-dark/fit.bin",
   "eyes": {
    "L": {
     "c": [
      0.2752,
      -0.1169,
      0.4573
     ],
     "r": 0.2529,
     "axis": [
      0.1457,
      -0.0004,
      0.9893
     ],
     "iris": 22.5,
     "pupil": 9.5
    },
    "R": {
     "c": [
      -0.2752,
      -0.1169,
      0.4573
     ],
     "r": 0.2529,
     "axis": [
      -0.1457,
      -0.0004,
      0.9893
     ],
     "iris": 22.5,
     "pupil": 9.5
    }
   },
   "lm": {
    "nose": [
     0,
     -0.399,
     0.9508
    ],
    "mouthL": [
     0.2621,
     -0.5988,
     0.6793
    ],
    "mouthR": [
     -0.2621,
     -0.5988,
     0.6793
    ],
    "chin": [
     0,
     -1,
     0.5623
    ],
    "crown": 1,
    "bottom": -1,
    "temple": 0.8957,
    "jaw": 0.5886
   }
  },
  {
   "id": "oldwoman-light",
   "group": "oldwoman",
   "tone": "light",
   "face": "/avatar/headz/oldwoman-light/face.glb",
   "lod": "/avatar/headz/oldwoman-light/face-lod.glb",
   "bytes": 858748,
   "tris": 33348,
   "skin": "#c5a093",
   "hair": "#cecbc7",
   "iris": "#8fbed4",
   "defaults": {
    "hair": "9"
   },
   "fit": "/avatar/headz/oldwoman-light/fit.bin",
   "eyes": {
    "L": {
     "c": [
      0.349,
      -0.0217,
      0.4054
     ],
     "r": 0.174,
     "axis": [
      0.0185,
      -0.006,
      0.9998
     ],
     "iris": 24.6,
     "pupil": 10.3
    },
    "R": {
     "c": [
      -0.349,
      -0.0217,
      0.4054
     ],
     "r": 0.174,
     "axis": [
      -0.0185,
      -0.006,
      0.9998
     ],
     "iris": 24.6,
     "pupil": 10.3
    }
   },
   "lm": {
    "nose": [
     0,
     -0.3224,
     0.8948
    ],
    "mouthL": [
     0.1989,
     -0.5854,
     0.5765
    ],
    "mouthR": [
     -0.1989,
     -0.5854,
     0.5765
    ],
    "chin": [
     0,
     -1,
     0.561
    ],
    "crown": 1,
    "bottom": -1,
    "temple": 0.8215,
    "jaw": 0.6722
   }
  },
  {
   "id": "oldwoman-medium",
   "group": "oldwoman",
   "tone": "medium",
   "face": "/avatar/headz/oldwoman-medium/face.glb",
   "lod": "/avatar/headz/oldwoman-medium/face-lod.glb",
   "bytes": 1051712,
   "tris": 33884,
   "skin": "#91796b",
   "hair": "#cecbc7",
   "iris": "#ab8c89",
   "defaults": {
    "hair": "1"
   },
   "fit": "/avatar/headz/oldwoman-medium/fit.bin",
   "eyes": {
    "L": {
     "c": [
      0.3164,
      -0.0392,
      0.4091
     ],
     "r": 0.1537,
     "axis": [
      0.039,
      -0.006,
      0.9992
     ],
     "iris": 24.6,
     "pupil": 10.3
    },
    "R": {
     "c": [
      -0.3164,
      -0.0392,
      0.4091
     ],
     "r": 0.1537,
     "axis": [
      -0.039,
      -0.006,
      0.9992
     ],
     "iris": 24.6,
     "pupil": 10.3
    }
   },
   "lm": {
    "nose": [
     0,
     -0.325,
     0.8783
    ],
    "mouthL": [
     0.2145,
     -0.5766,
     0.5523
    ],
    "mouthR": [
     -0.2145,
     -0.5766,
     0.5523
    ],
    "chin": [
     0,
     -1,
     0.5072
    ],
    "crown": 1,
    "bottom": -1,
    "temple": 0.85,
    "jaw": 0.7014
   }
  },
  {
   "id": "oldwoman-dark",
   "group": "oldwoman",
   "tone": "dark",
   "face": "/avatar/headz/oldwoman-dark/face.glb",
   "lod": "/avatar/headz/oldwoman-dark/face-lod.glb",
   "bytes": 1050468,
   "tris": 33884,
   "skin": "#6e4330",
   "hair": "#cecbc7",
   "iris": "#ab8c89",
   "defaults": {
    "hair": "1"
   },
   "fit": "/avatar/headz/oldwoman-dark/fit.bin",
   "eyes": {
    "L": {
     "c": [
      0.3137,
      -0.0303,
      0.4062
     ],
     "r": 0.1524,
     "axis": [
      0.039,
      -0.006,
      0.9992
     ],
     "iris": 24.6,
     "pupil": 10.3
    },
    "R": {
     "c": [
      -0.3137,
      -0.0303,
      0.4062
     ],
     "r": 0.1524,
     "axis": [
      -0.039,
      -0.006,
      0.9992
     ],
     "iris": 24.6,
     "pupil": 10.3
    }
   },
   "lm": {
    "nose": [
     0,
     -0.3142,
     0.8703
    ],
    "mouthL": [
     0.2127,
     -0.5628,
     0.5482
    ],
    "mouthR": [
     -0.2127,
     -0.5628,
     0.5482
    ],
    "chin": [
     0,
     -1,
     0.5504
    ],
    "crown": 1,
    "bottom": -1,
    "temple": 0.8428,
    "jaw": 0.6954
   }
  },
  {
   "id": "oldman-light",
   "group": "oldman",
   "tone": "light",
   "face": "/avatar/headz/oldman-light/face.glb",
   "lod": "/avatar/headz/oldman-light/face-lod.glb",
   "bytes": 850988,
   "tris": 33244,
   "skin": "#e8bdae",
   "hair": "#cecbc7",
   "iris": "#8fbed4",
   "defaults": {
    "hair": "4"
   },
   "fit": "/avatar/headz/oldman-light/fit.bin",
   "eyes": {
    "L": {
     "c": [
      0.3074,
      0.0463,
      0.4343
     ],
     "r": 0.1836,
     "axis": [
      0.0185,
      -0.0561,
      0.9983
     ],
     "iris": 24.6,
     "pupil": 10.3
    },
    "R": {
     "c": [
      -0.3074,
      0.0463,
      0.4343
     ],
     "r": 0.1836,
     "axis": [
      -0.0185,
      -0.0561,
      0.9983
     ],
     "iris": 24.6,
     "pupil": 10.3
    }
   },
   "lm": {
    "nose": [
     0,
     -0.3389,
     0.9392
    ],
    "mouthL": [
     0.0324,
     -0.8231,
     -0.054
    ],
    "mouthR": [
     0,
     -0.8254,
     -0.0531
    ],
    "chin": [
     0,
     -1,
     0.6309
    ],
    "crown": 1,
    "bottom": -1,
    "temple": 0.8183,
    "jaw": 0.442
   }
  },
  {
   "id": "oldman-medium",
   "group": "oldman",
   "tone": "medium",
   "face": "/avatar/headz/oldman-medium/face.glb",
   "lod": "/avatar/headz/oldman-medium/face-lod.glb",
   "bytes": 747456,
   "tris": 30596,
   "skin": "#b07550",
   "hair": "#cecbc7",
   "iris": "#a6938a",
   "defaults": {
    "hair": "5"
   },
   "fit": "/avatar/headz/oldman-medium/fit.bin",
   "eyes": {
    "L": {
     "c": [
      0.2745,
      0.0424,
      0.1883
     ],
     "r": 0.1774,
     "axis": [
      0.1181,
      -0.0767,
      0.99
     ],
     "iris": 24.6,
     "pupil": 10.3
    },
    "R": {
     "c": [
      -0.2742,
      0.0424,
      0.1883
     ],
     "r": 0.1774,
     "axis": [
      -0.1181,
      -0.0767,
      0.99
     ],
     "iris": 24.6,
     "pupil": 10.3
    }
   },
   "lm": {
    "nose": [
     0.0001,
     -0.293,
     0.8278
    ],
    "mouthL": [
     0.2308,
     -0.6347,
     0.4087
    ],
    "mouthR": [
     -0.2305,
     -0.6347,
     0.4087
    ],
    "chin": [
     0.107,
     -1,
     0.4022
    ],
    "crown": 1,
    "bottom": -1,
    "temple": 0.7173,
    "jaw": 0.6168
   }
  },
  {
   "id": "oldman-dark",
   "group": "oldman",
   "tone": "dark",
   "face": "/avatar/headz/oldman-dark/face.glb",
   "lod": "/avatar/headz/oldman-dark/face-lod.glb",
   "bytes": 745000,
   "tris": 30596,
   "skin": "#6e4330",
   "hair": "#cecbc7",
   "iris": "#a6938a",
   "defaults": {
    "hair": "4"
   },
   "fit": "/avatar/headz/oldman-dark/fit.bin",
   "eyes": {
    "L": {
     "c": [
      0.2749,
      0.0405,
      0.2391
     ],
     "r": 0.1778,
     "axis": [
      0.1181,
      -0.0767,
      0.99
     ],
     "iris": 24.6,
     "pupil": 10.3
    },
    "R": {
     "c": [
      -0.2749,
      0.0405,
      0.2391
     ],
     "r": 0.1778,
     "axis": [
      -0.1181,
      -0.0767,
      0.99
     ],
     "iris": 24.6,
     "pupil": 10.3
    }
   },
   "lm": {
    "nose": [
     0,
     -0.2955,
     0.7791
    ],
    "mouthL": [
     0.2165,
     -0.6367,
     0.4533
    ],
    "mouthR": [
     -0.2165,
     -0.6367,
     0.4533
    ],
    "chin": [
     0,
     -1,
     0.4599
    ],
    "crown": 1,
    "bottom": -1,
    "temple": 0.7192,
    "jaw": 0.5359
   }
  }
 ],
 "options": {
  "boy": {
   "hair": [
    {
     "id": "1",
     "files": {
      "boy-dark": "/avatar/headz/boy/hair-1-3883ad77.glb",
      "boy-light": "/avatar/headz/boy/hair-1-3883ad77.glb",
      "boy-medium": "/avatar/headz/boy/hair-1-3883ad77.glb"
     },
     "color": "#72351c",
     "bytes": 64092,
     "tris": 14000
    },
    {
     "id": "2",
     "files": {
      "boy-dark": "/avatar/headz/boy/hair-2-e63db238.glb",
      "boy-light": "/avatar/headz/boy/hair-2-e63db238.glb",
      "boy-medium": "/avatar/headz/boy/hair-2-e63db238.glb"
     },
     "color": "#72351c",
     "bytes": 81928,
     "tris": 17662
    },
    {
     "id": "3",
     "files": {
      "boy-dark": "/avatar/headz/boy/hair-3-72311947.glb",
      "boy-light": "/avatar/headz/boy/hair-3-72311947.glb",
      "boy-medium": "/avatar/headz/boy/hair-3-72311947.glb"
     },
     "color": "#72351c",
     "bytes": 67428,
     "tris": 14000
    },
    {
     "id": "4",
     "files": {
      "boy-dark": "/avatar/headz/boy/hair-4-ad6e41f4.glb",
      "boy-light": "/avatar/headz/boy/hair-4-ad6e41f4.glb",
      "boy-medium": "/avatar/headz/boy/hair-4-ad6e41f4.glb"
     },
     "color": "#72351c",
     "bytes": 114756,
     "tris": 24838
    },
    {
     "id": "5",
     "files": {
      "boy-dark": "/avatar/headz/boy/hair-5-9e8e3252.glb",
      "boy-light": "/avatar/headz/boy/hair-5-9e8e3252.glb",
      "boy-medium": "/avatar/headz/boy/hair-5-9e8e3252.glb"
     },
     "color": "#72351c",
     "bytes": 61112,
     "tris": 14000
    },
    {
     "id": "6",
     "files": {
      "boy-dark": "/avatar/headz/boy/hair-6-f14fc37f.glb",
      "boy-light": "/avatar/headz/boy/hair-6-f14fc37f.glb",
      "boy-medium": "/avatar/headz/boy/hair-6-e04d10b0.glb"
     },
     "color": "#72351c",
     "bytes": 67064,
     "tris": 14000
    },
    {
     "id": "7",
     "files": {
      "boy-dark": "/avatar/headz/boy/hair-7-77626f3a.glb",
      "boy-light": "/avatar/headz/boy/hair-7-77626f3a.glb",
      "boy-medium": "/avatar/headz/boy/hair-7-77626f3a.glb"
     },
     "color": "#72351c",
     "bytes": 68496,
     "tris": 14000
    },
    {
     "id": "8",
     "files": {
      "boy-dark": "/avatar/headz/boy/hair-8-6c088c34.glb",
      "boy-light": "/avatar/headz/boy/hair-8-6c088c34.glb",
      "boy-medium": "/avatar/headz/boy/hair-8-6c088c34.glb"
     },
     "color": "#72351c",
     "bytes": 64980,
     "tris": 13998
    },
    {
     "id": "9",
     "files": {
      "boy-dark": "/avatar/headz/boy/hair-9-ca7d165e.glb",
      "boy-light": "/avatar/headz/boy/hair-9-ca7d165e.glb",
      "boy-medium": "/avatar/headz/boy/hair-9-ca7d165e.glb"
     },
     "color": "#72351c",
     "bytes": 86964,
     "tris": 18698
    },
    {
     "id": "10",
     "files": {
      "boy-dark": "/avatar/headz/boy/hair-10-f08be77b.glb",
      "boy-light": "/avatar/headz/boy/hair-10-f08be77b.glb",
      "boy-medium": "/avatar/headz/boy/hair-10-f08be77b.glb"
     },
     "color": "#72351c",
     "bytes": 26500,
     "tris": 6080
    }
   ],
   "beard": [],
   "eyewear": [
    {
     "id": "eyeglasses-1",
     "files": {
      "boy-dark": "/avatar/headz/boy/eyewear-eyeglasses-1-db3a0c74.glb",
      "boy-light": "/avatar/headz/boy/eyewear-eyeglasses-1-db3a0c74.glb",
      "boy-medium": "/avatar/headz/boy/eyewear-eyeglasses-1-db3a0c74.glb"
     },
     "color": "#1d1d1d",
     "bytes": 25324,
     "tris": 5000
    },
    {
     "id": "eyeglasses-2",
     "files": {
      "boy-dark": "/avatar/headz/boy/eyewear-eyeglasses-2-763b0d31.glb",
      "boy-light": "/avatar/headz/boy/eyewear-eyeglasses-2-763b0d31.glb",
      "boy-medium": "/avatar/headz/boy/eyewear-eyeglasses-2-763b0d31.glb"
     },
     "color": "#d4f2ff",
     "bytes": 22612,
     "tris": 5000
    }
   ],
   "headwear": [
    {
     "id": "beanie-blue-spike",
     "files": {
      "boy-dark": "/avatar/headz/boy/headwear-beanie-blue-spike-69a6161a.glb",
      "boy-light": "/avatar/headz/boy/headwear-beanie-blue-spike-69a6161a.glb",
      "boy-medium": "/avatar/headz/boy/headwear-beanie-blue-spike-69a6161a.glb"
     },
     "color": "#b58900",
     "bytes": 24396,
     "tris": 5000,
     "rims": {
      "boy-dark": [
       0.207,
       -0.703
      ],
      "boy-light": [
       0.207,
       -0.703
      ],
      "boy-medium": [
       0.207,
       -0.703
      ]
     }
    },
    {
     "id": "beanie-yellow",
     "files": {
      "boy-dark": "/avatar/headz/boy/headwear-beanie-yellow-ef54e0b8.glb",
      "boy-light": "/avatar/headz/boy/headwear-beanie-yellow-ef54e0b8.glb",
      "boy-medium": "/avatar/headz/boy/headwear-beanie-yellow-ef54e0b8.glb"
     },
     "color": "#313131",
     "bytes": 23260,
     "tris": 5000,
     "rims": {
      "boy-dark": [
       0.863,
       -0.523
      ],
      "boy-light": [
       0.863,
       -0.523
      ],
      "boy-medium": [
       0.863,
       -0.523
      ]
     }
    },
    {
     "id": "cap",
     "files": {
      "boy-dark": "/avatar/headz/boy/headwear-cap-ded53a9c.glb",
      "boy-light": "/avatar/headz/boy/headwear-cap-ded53a9c.glb",
      "boy-medium": "/avatar/headz/boy/headwear-cap-ded53a9c.glb"
     },
     "color": "#273767",
     "bytes": 23928,
     "tris": 5000,
     "rims": {
      "boy-dark": [
       0.46,
       -0.174
      ],
      "boy-light": [
       0.46,
       -0.174
      ],
      "boy-medium": [
       0.46,
       -0.174
      ]
     }
    },
    {
     "id": "hat",
     "files": {
      "boy-dark": "/avatar/headz/boy/headwear-hat-c3131461.glb",
      "boy-light": "/avatar/headz/boy/headwear-hat-c3131461.glb",
      "boy-medium": "/avatar/headz/boy/headwear-hat-c3131461.glb"
     },
     "color": "#5d4288",
     "bytes": 22580,
     "tris": 5000,
     "rims": {
      "boy-dark": [
       0.748,
       -0.393
      ],
      "boy-light": [
       0.748,
       -0.393
      ],
      "boy-medium": [
       0.748,
       -0.393
      ]
     }
    }
   ],
   "earrings": [],
   "mask": [
    {
     "id": "mask",
     "files": {
      "boy-dark": "/avatar/headz/boy/mask-mask-d94bcb7f.glb",
      "boy-light": "/avatar/headz/boy/mask-mask-3ee61ab1.glb",
      "boy-medium": "/avatar/headz/boy/mask-mask-d94bcb7f.glb"
     },
     "color": "#e7e7e7",
     "bytes": 39076,
     "tris": 8000
    }
   ]
  },
  "girl": {
   "hair": [
    {
     "id": "1",
     "files": {
      "girl-dark": "/avatar/headz/girl/hair-1-ab7564e0.glb",
      "girl-light": "/avatar/headz/girl/hair-1-4124554d.glb",
      "girl-medium": "/avatar/headz/girl/hair-1-f703dde2.glb"
     },
     "color": "#72351c",
     "bytes": 69304,
     "tris": 14000
    },
    {
     "id": "2",
     "files": {
      "girl-dark": "/avatar/headz/girl/hair-2-59cb8a24.glb",
      "girl-light": "/avatar/headz/girl/hair-2-d373076c.glb",
      "girl-medium": "/avatar/headz/girl/hair-2-1bedde6d.glb"
     },
     "color": "#72351c",
     "bytes": 66808,
     "tris": 13999
    },
    {
     "id": "3",
     "files": {
      "girl-dark": "/avatar/headz/girl/hair-3-66b7d360.glb",
      "girl-light": "/avatar/headz/girl/hair-3-1a5ab6ab.glb",
      "girl-medium": "/avatar/headz/girl/hair-3-7bb87454.glb"
     },
     "color": "#72351c",
     "bytes": 67888,
     "tris": 14000
    },
    {
     "id": "4",
     "files": {
      "girl-dark": "/avatar/headz/girl/hair-4-82428ac4.glb",
      "girl-light": "/avatar/headz/girl/hair-4-4dc5ba06.glb",
      "girl-medium": "/avatar/headz/girl/hair-4-db42930a.glb"
     },
     "color": "#72351c",
     "bytes": 64860,
     "tris": 13999
    },
    {
     "id": "5",
     "files": {
      "girl-dark": "/avatar/headz/girl/hair-5-2f47cf92.glb",
      "girl-light": "/avatar/headz/girl/hair-5-ac1c6bbe.glb",
      "girl-medium": "/avatar/headz/girl/hair-5-c15e19c3.glb"
     },
     "color": "#72351c",
     "bytes": 66332,
     "tris": 13999
    },
    {
     "id": "6",
     "files": {
      "girl-dark": "/avatar/headz/girl/hair-6-c6e56cbd.glb",
      "girl-light": "/avatar/headz/girl/hair-6-ce6fd89f.glb",
      "girl-medium": "/avatar/headz/girl/hair-6-11bd2720.glb"
     },
     "color": "#72351c",
     "bytes": 69092,
     "tris": 13999
    },
    {
     "id": "7",
     "files": {
      "girl-dark": "/avatar/headz/girl/hair-7-81da66cf.glb",
      "girl-light": "/avatar/headz/girl/hair-7-d76a9bda.glb",
      "girl-medium": "/avatar/headz/girl/hair-7-570581f5.glb"
     },
     "color": "#72351c",
     "bytes": 70432,
     "tris": 14000
    },
    {
     "id": "8",
     "files": {
      "girl-dark": "/avatar/headz/girl/hair-8-0b80ec17.glb",
      "girl-light": "/avatar/headz/girl/hair-8-69717676.glb",
      "girl-medium": "/avatar/headz/girl/hair-8-bd999ac3.glb"
     },
     "color": "#72351c",
     "bytes": 31052,
     "tris": 6864
    },
    {
     "id": "9",
     "files": {
      "girl-dark": "/avatar/headz/girl/hair-9-b0730f39.glb",
      "girl-light": "/avatar/headz/girl/hair-9-8a5bb4da.glb",
      "girl-medium": "/avatar/headz/girl/hair-9-e5e5a549.glb"
     },
     "color": "#e7c870",
     "bytes": 71884,
     "tris": 14000
    },
    {
     "id": "10",
     "files": {
      "girl-light": "/avatar/headz/girl/hair-10-8a7dc3ea.glb"
     },
     "color": "#260e0d",
     "bytes": 65536,
     "tris": 14000
    }
   ],
   "beard": [],
   "eyewear": [
    {
     "id": "glasses-blue",
     "files": {
      "girl-dark": "/avatar/headz/girl/eyewear-glasses-blue-997ccefb.glb",
      "girl-light": "/avatar/headz/girl/eyewear-glasses-blue-ace6a307.glb",
      "girl-medium": "/avatar/headz/girl/eyewear-glasses-blue-e9998a9c.glb"
     },
     "color": "#02070d",
     "bytes": 23356,
     "tris": 5000
    },
    {
     "id": "glasses-red",
     "files": {
      "girl-dark": "/avatar/headz/girl/eyewear-glasses-red-4f0f8ed0.glb",
      "girl-light": "/avatar/headz/girl/eyewear-glasses-red-05f97219.glb",
      "girl-medium": "/avatar/headz/girl/eyewear-glasses-red-7234ee0b.glb"
     },
     "color": "#a11100",
     "bytes": 22688,
     "tris": 5000
    }
   ],
   "headwear": [
    {
     "id": "beanie-pink",
     "files": {
      "girl-dark": "/avatar/headz/girl/headwear-beanie-pink-4ebeee14.glb",
      "girl-light": "/avatar/headz/girl/headwear-beanie-pink-540ea8e3.glb",
      "girl-medium": "/avatar/headz/girl/headwear-beanie-pink-1bec5d9a.glb"
     },
     "color": "#ff7aa1",
     "bytes": 23092,
     "tris": 4999,
     "rims": {
      "girl-dark": [
       0.875,
       -0.65
      ],
      "girl-light": [
       0.908,
       -0.686
      ],
      "girl-medium": [
       0.874,
       -0.651
      ]
     }
    },
    {
     "id": "cap-yellow",
     "files": {
      "girl-dark": "/avatar/headz/girl/headwear-cap-yellow-c9359bc2.glb",
      "girl-light": "/avatar/headz/girl/headwear-cap-yellow-eb21d5b9.glb",
      "girl-medium": "/avatar/headz/girl/headwear-cap-yellow-cf493145.glb"
     },
     "color": "#000000",
     "bytes": 24568,
     "tris": 5000,
     "rims": {
      "girl-dark": [
       0.607,
       -0.288
      ],
      "girl-light": [
       0.67,
       -0.204
      ],
      "girl-medium": [
       0.607,
       -0.288
      ]
     }
    },
    {
     "id": "hat-pink",
     "files": {
      "girl-dark": "/avatar/headz/girl/headwear-hat-pink-3182f24e.glb",
      "girl-light": "/avatar/headz/girl/headwear-hat-pink-636f35b3.glb",
      "girl-medium": "/avatar/headz/girl/headwear-hat-pink-b032063f.glb"
     },
     "color": "#e7e7e7",
     "bytes": 22556,
     "tris": 5000,
     "rims": {
      "girl-dark": [
       0.612,
       -0.646
      ],
      "girl-light": [
       0.618,
       -0.463
      ],
      "girl-medium": [
       0.612,
       -0.647
      ]
     }
    }
   ],
   "earrings": [],
   "mask": [
    {
     "id": "mask",
     "files": {
      "girl-dark": "/avatar/headz/girl/mask-mask-01d83a2b.glb",
      "girl-light": "/avatar/headz/girl/mask-mask-7f7bba02.glb",
      "girl-medium": "/avatar/headz/girl/mask-mask-b4909f8e.glb"
     },
     "color": "#e7e7e7",
     "bytes": 38844,
     "tris": 8000
    }
   ]
  },
  "man": {
   "hair": [
    {
     "id": "001",
     "files": {
      "man-dark": "/avatar/headz/man/hair-001-1039e934.glb",
      "man-light": "/avatar/headz/man/hair-001-3ffcbe01.glb",
      "man-medium": "/avatar/headz/man/hair-001-1039e934.glb"
     },
     "color": "#141414",
     "bytes": 61756,
     "tris": 14000
    },
    {
     "id": "002",
     "files": {
      "man-dark": "/avatar/headz/man/hair-002-f20892c5.glb",
      "man-light": "/avatar/headz/man/hair-002-3d5b8798.glb",
      "man-medium": "/avatar/headz/man/hair-002-f20892c5.glb"
     },
     "color": "#141414",
     "bytes": 61016,
     "tris": 13999
    },
    {
     "id": "003",
     "files": {
      "man-light": "/avatar/headz/man/hair-003-02b56d0a.glb"
     },
     "color": "#0a0504",
     "bytes": 55712,
     "tris": 13952
    },
    {
     "id": "003-001",
     "files": {
      "man-dark": "/avatar/headz/man/hair-003-001-8e59d563.glb",
      "man-medium": "/avatar/headz/man/hair-003-001-8e59d563.glb"
     },
     "color": "#141414",
     "bytes": 55640,
     "tris": 13952
    },
    {
     "id": "003-002",
     "files": {
      "man-dark": "/avatar/headz/man/hair-003-002-fd99c05a.glb",
      "man-medium": "/avatar/headz/man/hair-003-002-fd99c05a.glb"
     },
     "color": "#141414",
     "bytes": 24688,
     "tris": 5696
    },
    {
     "id": "004",
     "files": {
      "man-dark": "/avatar/headz/man/hair-004-dfaa499c.glb",
      "man-light": "/avatar/headz/man/hair-004-fe04d5cc.glb",
      "man-medium": "/avatar/headz/man/hair-004-dfaa499c.glb"
     },
     "color": "#141414",
     "bytes": 62540,
     "tris": 13999
    },
    {
     "id": "005",
     "files": {
      "man-dark": "/avatar/headz/man/hair-005-f6f04329.glb",
      "man-light": "/avatar/headz/man/hair-005-425d010d.glb",
      "man-medium": "/avatar/headz/man/hair-005-f6f04329.glb"
     },
     "color": "#141414",
     "bytes": 64696,
     "tris": 14000
    },
    {
     "id": "006",
     "files": {
      "man-dark": "/avatar/headz/man/hair-006-f0fda1ef.glb",
      "man-light": "/avatar/headz/man/hair-006-499c09b1.glb",
      "man-medium": "/avatar/headz/man/hair-006-f0fda1ef.glb"
     },
     "color": "#141414",
     "bytes": 63772,
     "tris": 13999
    },
    {
     "id": "007",
     "files": {
      "man-dark": "/avatar/headz/man/hair-007-98428454.glb",
      "man-light": "/avatar/headz/man/hair-007-226b29ec.glb",
      "man-medium": "/avatar/headz/man/hair-007-98428454.glb"
     },
     "color": "#141414",
     "bytes": 43100,
     "tris": 11264
    },
    {
     "id": "008",
     "files": {
      "man-dark": "/avatar/headz/man/hair-008-fdcf6f70.glb",
      "man-light": "/avatar/headz/man/hair-008-bd658b10.glb",
      "man-medium": "/avatar/headz/man/hair-008-fdcf6f70.glb"
     },
     "color": "#141414",
     "bytes": 63872,
     "tris": 14000
    },
    {
     "id": "009",
     "files": {
      "man-dark": "/avatar/headz/man/hair-009-d78b5003.glb",
      "man-light": "/avatar/headz/man/hair-009-96cb347a.glb",
      "man-medium": "/avatar/headz/man/hair-009-d78b5003.glb"
     },
     "color": "#141414",
     "bytes": 62240,
     "tris": 14000
    },
    {
     "id": "hair011",
     "files": {
      "man-dark": "/avatar/headz/man/hair-hair011-dafb07c3.glb",
      "man-light": "/avatar/headz/man/hair-hair011-f6e28f72.glb",
      "man-medium": "/avatar/headz/man/hair-hair011-dafb07c3.glb"
     },
     "color": "#191919",
     "bytes": 79416,
     "tris": 14000
    },
    {
     "id": "hair012",
     "files": {
      "man-light": "/avatar/headz/man/hair-hair012-948f624c.glb"
     },
     "color": "#acacac",
     "bytes": 43356,
     "tris": 10640
    }
   ],
   "beard": [
    {
     "id": "beard01",
     "files": {
      "man-dark": "/avatar/headz/man/beard-beard01-f6188da3.glb",
      "man-light": "/avatar/headz/man/beard-beard01-0fcbf83f.glb",
      "man-medium": "/avatar/headz/man/beard-beard01-f6188da3.glb"
     },
     "color": "#191919",
     "bytes": 18760,
     "tris": 4144
    },
    {
     "id": "beard02",
     "files": {
      "man-dark": "/avatar/headz/man/beard-beard02-2f2600c9.glb",
      "man-light": "/avatar/headz/man/beard-beard02-67ebfef1.glb",
      "man-medium": "/avatar/headz/man/beard-beard02-2f2600c9.glb"
     },
     "color": "#000000",
     "bytes": 35284,
     "tris": 8000
    },
    {
     "id": "beard03",
     "files": {
      "man-light": "/avatar/headz/man/beard-beard03-752362a4.glb"
     },
     "color": "#2a2a2a",
     "bytes": 37192,
     "tris": 8000
    },
    {
     "id": "moustache-4",
     "files": {
      "man-dark": "/avatar/headz/man/beard-moustache-4-255107a5.glb",
      "man-medium": "/avatar/headz/man/beard-moustache-4-255107a5.glb"
     },
     "color": "#2a2a2a",
     "bytes": 36892,
     "tris": 8000
    },
    {
     "id": "moustache1",
     "files": {
      "man-light": "/avatar/headz/man/beard-moustache1-5756efb2.glb"
     },
     "color": "#191919",
     "bytes": 6496,
     "tris": 1088
    },
    {
     "id": "mustache-001",
     "files": {
      "man-dark": "/avatar/headz/man/beard-mustache-001-d95f7ce6.glb",
      "man-light": "/avatar/headz/man/beard-mustache-001-e56c6a52.glb",
      "man-medium": "/avatar/headz/man/beard-mustache-001-d95f7ce6.glb"
     },
     "color": "#141414",
     "bytes": 10304,
     "tris": 1664
    },
    {
     "id": "mustache-002",
     "files": {
      "man-dark": "/avatar/headz/man/beard-mustache-002-e260ffdf.glb",
      "man-light": "/avatar/headz/man/beard-mustache-002-e12eab0d.glb",
      "man-medium": "/avatar/headz/man/beard-mustache-002-e260ffdf.glb"
     },
     "color": "#141414",
     "bytes": 13120,
     "tris": 2432
    },
    {
     "id": "mustache-003",
     "files": {
      "man-dark": "/avatar/headz/man/beard-mustache-003-db36fae1.glb",
      "man-light": "/avatar/headz/man/beard-mustache-003-7a1290a7.glb",
      "man-medium": "/avatar/headz/man/beard-mustache-003-db36fae1.glb"
     },
     "color": "#141414",
     "bytes": 31448,
     "tris": 7488
    }
   ],
   "eyewear": [
    {
     "id": "glasses-001",
     "files": {
      "man-dark": "/avatar/headz/man/eyewear-glasses-001-4db45098.glb",
      "man-light": "/avatar/headz/man/eyewear-glasses-001-e4a71dd1.glb",
      "man-medium": "/avatar/headz/man/eyewear-glasses-001-4db45098.glb"
     },
     "color": "#000000",
     "bytes": 23516,
     "tris": 5000
    },
    {
     "id": "glasses-002",
     "files": {
      "man-dark": "/avatar/headz/man/eyewear-glasses-002-056c54a4.glb",
      "man-light": "/avatar/headz/man/eyewear-glasses-002-2a432aff.glb",
      "man-medium": "/avatar/headz/man/eyewear-glasses-002-056c54a4.glb"
     },
     "color": "#e7e1da",
     "bytes": 23572,
     "tris": 858
    },
    {
     "id": "glasses-003",
     "files": {
      "man-dark": "/avatar/headz/man/eyewear-glasses-003-e879ba3c.glb",
      "man-light": "/avatar/headz/man/eyewear-glasses-003-3f853512.glb",
      "man-medium": "/avatar/headz/man/eyewear-glasses-003-e879ba3c.glb"
     },
     "color": "#e7a300",
     "bytes": 22800,
     "tris": 836
    }
   ],
   "headwear": [
    {
     "id": "hat",
     "files": {
      "man-dark": "/avatar/headz/man/headwear-hat-d56b6733.glb",
      "man-light": "/avatar/headz/man/headwear-hat-4dbc1ee9.glb",
      "man-medium": "/avatar/headz/man/headwear-hat-d56b6733.glb"
     },
     "color": "#211d62",
     "bytes": 22160,
     "tris": 5000,
     "rims": {
      "man-dark": [
       0.509,
       0.122
      ],
      "man-light": [
       0.474,
       0.064
      ],
      "man-medium": [
       0.509,
       0.122
      ]
     }
    },
    {
     "id": "hat-2",
     "files": {
      "man-dark": "/avatar/headz/man/headwear-hat-2-1f95c3b7.glb",
      "man-medium": "/avatar/headz/man/headwear-hat-2-1f95c3b7.glb"
     },
     "color": "#e7e7e7",
     "bytes": 27624,
     "tris": 5000,
     "rims": {
      "man-dark": [
       0.327,
       0.202
      ],
      "man-medium": [
       0.327,
       0.202
      ]
     }
    }
   ],
   "earrings": [],
   "mask": [
    {
     "id": "mask",
     "files": {
      "man-dark": "/avatar/headz/man/mask-mask-9b84c098.glb",
      "man-medium": "/avatar/headz/man/mask-mask-9b84c098.glb"
     },
     "color": "#57c4b5",
     "bytes": 39336,
     "tris": 8000
    },
    {
     "id": "masker",
     "files": {
      "man-light": "/avatar/headz/man/mask-masker-cec41314.glb"
     },
     "color": "#57c4b5",
     "bytes": 38748,
     "tris": 8000
    }
   ]
  },
  "oldman": {
   "hair": [
    {
     "id": "1",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/hair-1-48724c64.glb",
      "oldman-light": "/avatar/headz/oldman/hair-1-d5a45502.glb",
      "oldman-medium": "/avatar/headz/oldman/hair-1-5a4afe12.glb"
     },
     "color": "#aebeb2",
     "bytes": 56972,
     "tris": 14000
    },
    {
     "id": "2",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/hair-2-e71e07b0.glb",
      "oldman-light": "/avatar/headz/oldman/hair-2-e7527985.glb",
      "oldman-medium": "/avatar/headz/oldman/hair-2-a816dd7b.glb"
     },
     "color": "#aebeb2",
     "bytes": 58008,
     "tris": 14000
    },
    {
     "id": "3",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/hair-3-9a6021ee.glb",
      "oldman-light": "/avatar/headz/oldman/hair-3-0adafe2c.glb",
      "oldman-medium": "/avatar/headz/oldman/hair-3-f97d06b5.glb"
     },
     "color": "#aebeb2",
     "bytes": 56660,
     "tris": 14000
    },
    {
     "id": "4",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/hair-4-dca493f6.glb",
      "oldman-light": "/avatar/headz/oldman/hair-4-bdee0a1f.glb",
      "oldman-medium": "/avatar/headz/oldman/hair-4-74c83b87.glb"
     },
     "color": "#aebeb2",
     "bytes": 58936,
     "tris": 14000
    },
    {
     "id": "5",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/hair-5-c76017e0.glb",
      "oldman-light": "/avatar/headz/oldman/hair-5-f373f75b.glb",
      "oldman-medium": "/avatar/headz/oldman/hair-5-7a96de46.glb"
     },
     "color": "#aebeb2",
     "bytes": 57840,
     "tris": 14000
    },
    {
     "id": "6",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/hair-6-3e864c3c.glb",
      "oldman-light": "/avatar/headz/oldman/hair-6-183d900d.glb",
      "oldman-medium": "/avatar/headz/oldman/hair-6-8dcb16c7.glb"
     },
     "color": "#aebeb2",
     "bytes": 59468,
     "tris": 14000
    },
    {
     "id": "7",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/hair-7-413edbbd.glb",
      "oldman-light": "/avatar/headz/oldman/hair-7-bf276afd.glb",
      "oldman-medium": "/avatar/headz/oldman/hair-7-147abfd0.glb"
     },
     "color": "#aebeb2",
     "bytes": 59684,
     "tris": 14000
    },
    {
     "id": "8",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/hair-8-2b888721.glb",
      "oldman-light": "/avatar/headz/oldman/hair-8-edce607a.glb",
      "oldman-medium": "/avatar/headz/oldman/hair-8-998348bd.glb"
     },
     "color": "#aebeb2",
     "bytes": 56212,
     "tris": 14000
    }
   ],
   "beard": [
    {
     "id": "beard",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/beard-beard-d4a0ad5f.glb",
      "oldman-light": "/avatar/headz/oldman/beard-beard-23661ba0.glb",
      "oldman-medium": "/avatar/headz/oldman/beard-beard-5bf24d11.glb"
     },
     "color": "#aebeb2",
     "bytes": 35984,
     "tris": 8000
    },
    {
     "id": "mustache",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/beard-mustache-3a46ea05.glb",
      "oldman-light": "/avatar/headz/oldman/beard-mustache-d3e3c128.glb",
      "oldman-medium": "/avatar/headz/oldman/beard-mustache-cf3d81c3.glb"
     },
     "color": "#aebeb2",
     "bytes": 33224,
     "tris": 2048
    }
   ],
   "eyewear": [
    {
     "id": "glasses-black",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/eyewear-glasses-black-7057536f.glb",
      "oldman-light": "/avatar/headz/oldman/eyewear-glasses-black-0f42c642.glb",
      "oldman-medium": "/avatar/headz/oldman/eyewear-glasses-black-27ce9b17.glb"
     },
     "color": "#10100f",
     "bytes": 23376,
     "tris": 5000
    },
    {
     "id": "glasses-black-small",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/eyewear-glasses-black-small-eebd2684.glb",
      "oldman-light": "/avatar/headz/oldman/eyewear-glasses-black-small-daaafcc0.glb",
      "oldman-medium": "/avatar/headz/oldman/eyewear-glasses-black-small-4fd1bf14.glb"
     },
     "color": "#292929",
     "bytes": 24868,
     "tris": 5000
    },
    {
     "id": "glasses-white",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/eyewear-glasses-white-ef2d1625.glb",
      "oldman-light": "/avatar/headz/oldman/eyewear-glasses-white-a2c6057e.glb",
      "oldman-medium": "/avatar/headz/oldman/eyewear-glasses-white-73837b97.glb"
     },
     "color": "#e7e1da",
     "bytes": 22468,
     "tris": 5000
    },
    {
     "id": "glasses-yellow",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/eyewear-glasses-yellow-97b13ecd.glb",
      "oldman-light": "/avatar/headz/oldman/eyewear-glasses-yellow-06d20d63.glb",
      "oldman-medium": "/avatar/headz/oldman/eyewear-glasses-yellow-60a9b5ba.glb"
     },
     "color": "#e7ae62",
     "bytes": 25176,
     "tris": 5000
    }
   ],
   "headwear": [
    {
     "id": "beanie-red",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/headwear-beanie-red-3a5c62c0.glb",
      "oldman-light": "/avatar/headz/oldman/headwear-beanie-red-45819bc9.glb",
      "oldman-medium": "/avatar/headz/oldman/headwear-beanie-red-6ce9c49d.glb"
     },
     "color": "#9d2c1d",
     "bytes": 26640,
     "tris": 5000,
     "rims": {
      "oldman-dark": [
       0.463,
       0.047
      ],
      "oldman-light": [
       0.508,
       -0.031
      ],
      "oldman-medium": [
       0.471,
       0.049
      ]
     }
    },
    {
     "id": "cap-green-white",
     "files": {
      "oldman-light": "/avatar/headz/oldman/headwear-cap-green-white-d21c5110.glb"
     },
     "color": "#85c8ac",
     "bytes": 25296,
     "tris": 5000,
     "rims": {
      "oldman-light": [
       0.36,
       0.433
      ]
     }
    },
    {
     "id": "cap-grey",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/headwear-cap-grey-e29d0353.glb",
      "oldman-light": "/avatar/headz/oldman/headwear-cap-grey-b9d6be32.glb",
      "oldman-medium": "/avatar/headz/oldman/headwear-cap-grey-122cf504.glb"
     },
     "color": "#626262",
     "bytes": 25072,
     "tris": 5000,
     "rims": {
      "oldman-dark": [
       0.299,
       -0.057
      ],
      "oldman-light": [
       0.414,
       -0.014
      ],
      "oldman-medium": [
       0.303,
       -0.055
      ]
     }
    },
    {
     "id": "hat-black",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/headwear-hat-black-bd96a51d.glb",
      "oldman-light": "/avatar/headz/oldman/headwear-hat-black-b08305a3.glb",
      "oldman-medium": "/avatar/headz/oldman/headwear-hat-black-47b84bec.glb"
     },
     "color": "#060606",
     "bytes": 26524,
     "tris": 5000,
     "rims": {
      "oldman-dark": [
       0.255,
       0.394
      ],
      "oldman-light": [
       0.294,
       0.489
      ],
      "oldman-medium": [
       0.257,
       0.395
      ]
     }
    },
    {
     "id": "hat-white",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/headwear-hat-white-2a7d98bf.glb",
      "oldman-light": "/avatar/headz/oldman/headwear-hat-white-66f25eaf.glb",
      "oldman-medium": "/avatar/headz/oldman/headwear-hat-white-aa53b75d.glb"
     },
     "color": "#f7f0f1",
     "bytes": 26340,
     "tris": 5000,
     "rims": {
      "oldman-dark": [
       0.162,
       -0.005
      ],
      "oldman-light": [
       0.259,
       0.231
      ],
      "oldman-medium": [
       0.164,
       -0.002
      ]
     }
    },
    {
     "id": "hat-yellow",
     "files": {
      "oldman-dark": "/avatar/headz/oldman/headwear-hat-yellow-1d3ac020.glb",
      "oldman-light": "/avatar/headz/oldman/headwear-hat-yellow-4aa89dbf.glb",
      "oldman-medium": "/avatar/headz/oldman/headwear-hat-yellow-357f2834.glb"
     },
     "color": "#e7b16c",
     "bytes": 27400,
     "tris": 5000,
     "rims": {
      "oldman-dark": [
       0.528,
       -0.117
      ],
      "oldman-light": [
       0.694,
       -0.067
      ],
      "oldman-medium": [
       0.529,
       -0.115
      ]
     }
    }
   ],
   "earrings": [],
   "mask": []
  },
  "oldwoman": {
   "hair": [
    {
     "id": "1",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-1-c359883d.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-1-eb87e580.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-1-4b6b3b7d.glb"
     },
     "color": "#aebeb2",
     "bytes": 56336,
     "tris": 14000
    },
    {
     "id": "2",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-2-f0e6ce0b.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-2-a659fb10.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-2-53a51f72.glb"
     },
     "color": "#aebeb2",
     "bytes": 58356,
     "tris": 14000
    },
    {
     "id": "3",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-3-fe4eea90.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-3-363d8cd7.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-3-746eb27b.glb"
     },
     "color": "#aebeb2",
     "bytes": 65848,
     "tris": 14000
    },
    {
     "id": "4",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-4-0efee9bf.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-4-95b5a300.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-4-285e28ac.glb"
     },
     "color": "#aebeb2",
     "bytes": 65108,
     "tris": 13999
    },
    {
     "id": "5",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-5-d3b3df64.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-5-3c7f199e.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-5-b19d9b42.glb"
     },
     "color": "#aebeb2",
     "bytes": 61640,
     "tris": 14000
    },
    {
     "id": "6",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-6-26cb5b75.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-6-dd4130fd.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-6-a7534ef1.glb"
     },
     "color": "#aebeb2",
     "bytes": 63992,
     "tris": 14000
    },
    {
     "id": "7",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-7-6b7c9682.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-7-930fa073.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-7-a0a25561.glb"
     },
     "color": "#aebeb2",
     "bytes": 58132,
     "tris": 14000
    },
    {
     "id": "8",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-8-9a572325.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-8-69de2301.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-8-485a2e26.glb"
     },
     "color": "#aebeb2",
     "bytes": 64988,
     "tris": 14000
    },
    {
     "id": "9",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-9-c142aaeb.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-9-c27be6c2.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-9-0ff9578b.glb"
     },
     "color": "#aebeb2",
     "bytes": 61024,
     "tris": 14000
    },
    {
     "id": "10",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-10-fdbb59e9.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-10-836d5803.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-10-5dff2d56.glb"
     },
     "color": "#aebeb2",
     "bytes": 62448,
     "tris": 14000
    },
    {
     "id": "11",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/hair-11-8ab8b2e5.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/hair-11-c9909127.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/hair-11-a4fbb218.glb"
     },
     "color": "#aebeb2",
     "bytes": 61568,
     "tris": 14000
    }
   ],
   "beard": [],
   "eyewear": [
    {
     "id": "glasses-black",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/eyewear-glasses-black-5f9856e8.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/eyewear-glasses-black-fa9d7392.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/eyewear-glasses-black-18196b47.glb"
     },
     "color": "#10100f",
     "bytes": 23208,
     "tris": 5000
    },
    {
     "id": "glasses-black-small",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/eyewear-glasses-black-small-3b7a4899.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/eyewear-glasses-black-small-9e0ffe04.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/eyewear-glasses-black-small-46e61379.glb"
     },
     "color": "#292929",
     "bytes": 24716,
     "tris": 5000
    },
    {
     "id": "glasses-red",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/eyewear-glasses-red-e7a5187c.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/eyewear-glasses-red-73c5235c.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/eyewear-glasses-red-d9806354.glb"
     },
     "color": "#a11100",
     "bytes": 22696,
     "tris": 5000
    },
    {
     "id": "glasses-white",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/eyewear-glasses-white-aef9a790.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/eyewear-glasses-white-1194187b.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/eyewear-glasses-white-88930441.glb"
     },
     "color": "#e7e1da",
     "bytes": 22636,
     "tris": 5000
    },
    {
     "id": "glasses-yellow",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/eyewear-glasses-yellow-50d673c0.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/eyewear-glasses-yellow-651980a7.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/eyewear-glasses-yellow-e5fa7006.glb"
     },
     "color": "#e7ae62",
     "bytes": 25468,
     "tris": 5000
    }
   ],
   "headwear": [
    {
     "id": "beanie-red",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/headwear-beanie-red-926a6d98.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/headwear-beanie-red-d947d4af.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/headwear-beanie-red-8b26d170.glb"
     },
     "color": "#9d2c1d",
     "bytes": 27284,
     "tris": 5000,
     "rims": {
      "oldwoman-dark": [
       0.485,
       -0.116
      ],
      "oldwoman-light": [
       0.386,
       -0.188
      ],
      "oldwoman-medium": [
       0.481,
       -0.125
      ]
     }
    },
    {
     "id": "cap-grey",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/headwear-cap-grey-39036259.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/headwear-cap-grey-7901eccd.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/headwear-cap-grey-91551a00.glb"
     },
     "color": "#626262",
     "bytes": 24812,
     "tris": 5000,
     "rims": {
      "oldwoman-dark": [
       0.353,
       -0.069
      ],
      "oldwoman-light": [
       0.33,
       -0.045
      ],
      "oldwoman-medium": [
       0.348,
       -0.078
      ]
     }
    },
    {
     "id": "hat-grey",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/headwear-hat-grey-17255487.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/headwear-hat-grey-5461302c.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/headwear-hat-grey-2edd45dd.glb"
     },
     "color": "#504e4f",
     "bytes": 24568,
     "tris": 5000,
     "rims": {
      "oldwoman-dark": [
       0.52,
       -0.383
      ],
      "oldwoman-light": [
       0.609,
       -0.331
      ],
      "oldwoman-medium": [
       0.516,
       -0.395
      ]
     }
    },
    {
     "id": "hat-yellow",
     "files": {
      "oldwoman-dark": "/avatar/headz/oldwoman/headwear-hat-yellow-14b96924.glb",
      "oldwoman-light": "/avatar/headz/oldwoman/headwear-hat-yellow-83aa0e06.glb",
      "oldwoman-medium": "/avatar/headz/oldwoman/headwear-hat-yellow-53919561.glb"
     },
     "color": "#e7b16c",
     "bytes": 27052,
     "tris": 5000,
     "rims": {
      "oldwoman-dark": [
       0.685,
       -0.142
      ],
      "oldwoman-light": [
       0.628,
       -0.387
      ],
      "oldwoman-medium": [
       0.682,
       -0.152
      ]
     }
    }
   ],
   "earrings": [],
   "mask": []
  },
  "woman": {
   "hair": [
    {
     "id": "001",
     "files": {
      "woman-dark": "/avatar/headz/woman/hair-001-e50057c5.glb",
      "woman-light": "/avatar/headz/woman/hair-001-711a3084.glb",
      "woman-medium": "/avatar/headz/woman/hair-001-e50057c5.glb"
     },
     "color": "#140505",
     "bytes": 56288,
     "tris": 13999
    },
    {
     "id": "002",
     "files": {
      "woman-dark": "/avatar/headz/woman/hair-002-f763618c.glb",
      "woman-light": "/avatar/headz/woman/hair-002-188c4611.glb",
      "woman-medium": "/avatar/headz/woman/hair-002-f763618c.glb"
     },
     "color": "#140505",
     "bytes": 60636,
     "tris": 14000
    },
    {
     "id": "003",
     "files": {
      "woman-dark": "/avatar/headz/woman/hair-003-fbd7196d.glb",
      "woman-light": "/avatar/headz/woman/hair-003-cee30aff.glb",
      "woman-medium": "/avatar/headz/woman/hair-003-fbd7196d.glb"
     },
     "color": "#140505",
     "bytes": 61128,
     "tris": 14000
    },
    {
     "id": "004",
     "files": {
      "woman-dark": "/avatar/headz/woman/hair-004-149b40be.glb",
      "woman-light": "/avatar/headz/woman/hair-004-21a5a6e1.glb",
      "woman-medium": "/avatar/headz/woman/hair-004-149b40be.glb"
     },
     "color": "#140505",
     "bytes": 62060,
     "tris": 14000
    },
    {
     "id": "005",
     "files": {
      "woman-dark": "/avatar/headz/woman/hair-005-133e70c4.glb",
      "woman-light": "/avatar/headz/woman/hair-005-049d27ec.glb",
      "woman-medium": "/avatar/headz/woman/hair-005-133e70c4.glb"
     },
     "color": "#140505",
     "bytes": 56708,
     "tris": 14000
    },
    {
     "id": "006",
     "files": {
      "woman-dark": "/avatar/headz/woman/hair-006-98e0f0f6.glb",
      "woman-light": "/avatar/headz/woman/hair-006-789c8058.glb",
      "woman-medium": "/avatar/headz/woman/hair-006-98e0f0f6.glb"
     },
     "color": "#140505",
     "bytes": 47140,
     "tris": 11136
    },
    {
     "id": "007",
     "files": {
      "woman-dark": "/avatar/headz/woman/hair-007-937e9e5e.glb",
      "woman-light": "/avatar/headz/woman/hair-007-b657c3c5.glb",
      "woman-medium": "/avatar/headz/woman/hair-007-937e9e5e.glb"
     },
     "color": "#140505",
     "bytes": 62560,
     "tris": 13999
    },
    {
     "id": "008",
     "files": {
      "woman-dark": "/avatar/headz/woman/hair-008-7dc74a84.glb",
      "woman-light": "/avatar/headz/woman/hair-008-040805fa.glb",
      "woman-medium": "/avatar/headz/woman/hair-008-7dc74a84.glb"
     },
     "color": "#140505",
     "bytes": 59744,
     "tris": 13999
    },
    {
     "id": "009",
     "files": {
      "woman-dark": "/avatar/headz/woman/hair-009-0f696eed.glb",
      "woman-light": "/avatar/headz/woman/hair-009-5adeae82.glb",
      "woman-medium": "/avatar/headz/woman/hair-009-0f696eed.glb"
     },
     "color": "#140505",
     "bytes": 64240,
     "tris": 13998
    },
    {
     "id": "010",
     "files": {
      "woman-dark": "/avatar/headz/woman/hair-010-66d95eda.glb",
      "woman-light": "/avatar/headz/woman/hair-010-be0e0e6f.glb",
      "woman-medium": "/avatar/headz/woman/hair-010-66d95eda.glb"
     },
     "color": "#140505",
     "bytes": 33168,
     "tris": 7808
    }
   ],
   "beard": [],
   "eyewear": [
    {
     "id": "glasses-001",
     "files": {
      "woman-dark": "/avatar/headz/woman/eyewear-glasses-001-0576f238.glb",
      "woman-light": "/avatar/headz/woman/eyewear-glasses-001-fab41bec.glb",
      "woman-medium": "/avatar/headz/woman/eyewear-glasses-001-0576f238.glb"
     },
     "color": "#e7e7e7",
     "bytes": 23400,
     "tris": 5000
    },
    {
     "id": "glasses-002",
     "files": {
      "woman-dark": "/avatar/headz/woman/eyewear-glasses-002-82ebb390.glb",
      "woman-light": "/avatar/headz/woman/eyewear-glasses-002-f556e1c4.glb",
      "woman-medium": "/avatar/headz/woman/eyewear-glasses-002-82ebb390.glb"
     },
     "color": "#e7e7e7",
     "bytes": 23768,
     "tris": 5000
    },
    {
     "id": "glasses-003",
     "files": {
      "woman-dark": "/avatar/headz/woman/eyewear-glasses-003-4d7df4ab.glb",
      "woman-light": "/avatar/headz/woman/eyewear-glasses-003-9930e80c.glb",
      "woman-medium": "/avatar/headz/woman/eyewear-glasses-003-4d7df4ab.glb"
     },
     "color": "#161616",
     "bytes": 22584,
     "tris": 5000
    }
   ],
   "headwear": [
    {
     "id": "hat",
     "files": {
      "woman-dark": "/avatar/headz/woman/headwear-hat-72a6110c.glb",
      "woman-light": "/avatar/headz/woman/headwear-hat-d30179fc.glb",
      "woman-medium": "/avatar/headz/woman/headwear-hat-72a6110c.glb"
     },
     "color": "#e7e7e7",
     "bytes": 24404,
     "tris": 4999,
     "rims": {
      "woman-dark": [
       0.757,
       -0.697
      ],
      "woman-light": [
       0.731,
       -0.589
      ],
      "woman-medium": [
       0.757,
       -0.697
      ]
     }
    }
   ],
   "earrings": [
    {
     "id": "earrings",
     "files": {
      "woman-dark": "/avatar/headz/woman/earrings-earrings-6d47d753.glb",
      "woman-light": "/avatar/headz/woman/earrings-earrings-b0ce4549.glb",
      "woman-medium": "/avatar/headz/woman/earrings-earrings-6d47d753.glb"
     },
     "color": "#e7d5a5",
     "bytes": 21604,
     "tris": 5000
    }
   ],
   "mask": [
    {
     "id": "mask",
     "files": {
      "woman-dark": "/avatar/headz/woman/mask-mask-2c2cbc78.glb",
      "woman-light": "/avatar/headz/woman/mask-mask-db12db54.glb",
      "woman-medium": "/avatar/headz/woman/mask-mask-2c2cbc78.glb"
     },
     "color": "#57c4b5",
     "bytes": 39128,
     "tris": 8000
    }
   ]
  }
 }
};
