/**
 * Types of the HEADZ runtime catalogue (generated by tools/headz/build.mjs into
 * catalog.gen.ts). Every base is one purchased HEADZ 2.0 character; parts are
 * optional meshes (hair, beards, glasses, hats, earrings) fitted to that base.
 */
export type HeadzGroup = "man" | "woman" | "boy" | "girl" | "oldman" | "oldwoman";
export type HeadzTone = "light" | "medium" | "dark";
export type HeadzSlot = "hair" | "beard" | "eyewear" | "headwear" | "earrings" | "mask";

export interface HeadzPartOption {
  /** stable option id within the group, e.g. "h3" */
  id: string;
  /** file per base id (bases of a group share files when the geometry is identical) */
  files: Record<string, string>;
  /** authored colour of the part (hex) */
  color: string;
  bytes: number;
  tris: number;
  /** headwear only: hat rim height (head space, +Y up) at the front and the back, per base — hair above it is clipped */
  rims?: Record<string, [number, number]>;
}

export interface HeadzBase {
  id: string;
  group: HeadzGroup;
  tone: HeadzTone;
  face: string;
  /** light static face (no morph targets) for list thumbnails */
  lod?: string;
  bytes: number;
  tris: number;
  /** authored colours (hex, sRGB) */
  skin: string;
  hair: string;
  iris: string;
  /** the part options this base was sold with (option ids by slot) */
  defaults: Partial<Record<HeadzSlot, string>>;
  /** spherical radius map of the head (uint8, see tools/headz) — fits parts made for other bases */
  fit?: string;
  /** eyeballs in head space: centre, radius, gaze axis, iris / pupil angular radius (degrees) */
  eyes?: Partial<Record<"L" | "R", HeadzEye>>;
  /** landmarks in head space (+Y up, +Z front) */
  lm?: HeadzLandmarks;
}

export interface HeadzEye {
  c: [number, number, number];
  r: number;
  axis: [number, number, number];
  iris: number;
  pupil: number;
}

export interface HeadzLandmarks {
  nose?: [number, number, number];
  mouthL?: [number, number, number];
  mouthR?: [number, number, number];
  chin?: [number, number, number];
  crown?: number;
  bottom?: number;
  temple?: number;
  jaw?: number;
  ear?: number;
}

export interface HeadzCatalog {
  version: string;
  bases: HeadzBase[];
  /** options by group then slot */
  options: Record<HeadzGroup, Record<HeadzSlot, HeadzPartOption[]>>;
}
