# Generated by Django 5.0.6 on 2026-09-25 12:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consultations", "0003_unique_active_start"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("event", models.CharField(max_length=40)),
                ("object_id", models.CharField(db_index=True, max_length=100)),
                ("result", models.CharField(blank=True, default="", max_length=40)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "received_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "db_table": "billing_webhook_event",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=80, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("client", "Баланс клиента"),
                            ("client_hold", "Заморожено под созвоны"),
                            ("spec_pending", "Заработок: ожидает"),
                            ("spec_available", "Заработок: доступно"),
                            ("spec_payout", "Заработок: в выплате"),
                            ("platform_fee", "Комиссия платформы"),
                            ("provider", "Платёжный провайдер"),
                            ("payouts_sent", "Выплачено специалистам"),
                            ("gift", "Подарочные коды"),
                            ("adjustment", "Корректировки"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("balance_kopecks", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Счёт",
                "db_table": "billing_account",
            },
        ),
        migrations.CreateModel(
            name="GiftBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=80)),
                ("amount_kopecks", models.BigIntegerField()),
                ("count", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "billing_gift_batch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GiftCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=64, unique=True)),
                ("hint", models.CharField(blank=True, default="", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Не погашен"),
                            ("redeemed", "Погашен"),
                            ("revoked", "Отозван"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codes",
                        to="billing.giftbatch",
                    ),
                ),
                (
                    "redeemed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "billing_gift_code",
            },
        ),
        migrations.CreateModel(
            name="Hold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_ref", models.UUIDField(db_index=True)),
                (
                    "client_ref",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=40
                    ),
                ),
                (
                    "specialist_ref",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=40
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Заморожено"),
                            ("captured", "Списано"),
                            ("released", "Возвращено"),
                            ("partial", "Частичный возврат"),
                            ("refunded", "Возвращено после созвона"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=12,
                    ),
                ),
                ("amount_kopecks", models.BigIntegerField()),
                ("specialist_kopecks", models.BigIntegerField(default=0)),
                ("fee_kopecks", models.BigIntegerField(default=0)),
                ("returned_kopecks", models.BigIntegerField(default=0)),
                ("reason", models.CharField(blank=True, default="", max_length=40)),
                ("duration_minutes", models.PositiveSmallIntegerField(default=0)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "available_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("matured", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_hold",
                        to="consultations.consultationsession",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "billing_hold",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("topup", "Пополнение"),
                            ("topup_refund", "Возврат пополнения на карту"),
                            ("topup_refund_reversal", "Отмена возврата"),
                            ("hold", "Оплата созвона (заморозка)"),
                            ("capture", "Созвон состоялся"),
                            ("release", "Возврат за созвон"),
                            ("call_refund", "Возврат за состоявшийся созвон"),
                            ("mature", "Заработок доступен"),
                            ("payout_request", "Запрос выплаты"),
                            ("payout_paid", "Выплата отправлена"),
                            ("payout_return", "Выплата отклонена"),
                            ("gift_redeem", "Подарочный код"),
                            ("adjustment", "Корректировка"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=120, unique=True)),
                ("session_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("memo", models.CharField(blank=True, default="", max_length=200)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Операция",
                "db_table": "billing_transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayoutMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("sbp", "СБП по номеру телефона"),
                            ("bank_account", "Банковский счёт"),
                            ("card_token", "Карта (токен ЮKassa)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tax_status",
                    models.CharField(
                        choices=[
                            ("self_employed", "Самозанятый (НПД)"),
                            ("ip", "Индивидуальный предприниматель"),
                        ],
                        default="self_employed",
                        max_length=20,
                    ),
                ),
                ("encrypted", models.BinaryField()),
                ("masked", models.CharField(blank=True, default="", max_length=80)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_method",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "billing_payout_method",
            },
        ),
        migrations.CreateModel(
            name="PayoutRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "specialist_ref",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=40
                    ),
                ),
                ("amount_kopecks", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Запрошена"),
                            ("processing", "Отправляется"),
                            ("paid", "Выплачена"),
                            ("rejected", "Отклонена"),
                            ("failed", "Не прошла"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=12,
                    ),
                ),
                ("rail", models.CharField(default="manual", max_length=20)),
                (
                    "destination_kind",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "destination_masked",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "provider_payout_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "billing_payout_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TopUp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_ref",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=40
                    ),
                ),
                ("provider", models.CharField(default="mock", max_length=20)),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("amount_kopecks", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("succeeded", "Зачислено"),
                            ("canceled", "Отменено"),
                            ("refunded", "Возвращено на карту"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("method", models.CharField(blank=True, default="", max_length=20)),
                (
                    "confirmation_type",
                    models.CharField(blank=True, default="redirect", max_length=12),
                ),
                (
                    "confirmation_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "confirmation_token",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("with_receipt", models.BooleanField(default=False)),
                (
                    "provider_refund_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("refunded_kopecks", models.BigIntegerField(default=0)),
                (
                    "cancel_reason",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "billing_topup",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_kopecks", models.BigIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="billing.account",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="billing.ledgertransaction",
                    ),
                ),
            ],
            options={
                "db_table": "billing_entry",
                "indexes": [
                    models.Index(
                        fields=["account", "created_at"],
                        name="billing_ent_account_f25472_idx",
                    )
                ],
            },
        ),
    ]
