# Generated by Django 5.0.6 on 2026-09-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="kind",
            field=models.CharField(
                choices=[
                    ("client", "Баланс клиента"),
                    ("client_hold", "Заморожено под созвоны"),
                    ("spec_pending", "Заработок: ожидает"),
                    ("spec_available", "Заработок: доступно"),
                    ("spec_payout", "Заработок: в выплате"),
                    ("platform_fee", "Комиссия платформы"),
                    ("provider", "Платёжный провайдер"),
                    ("payouts_sent", "Выплачено специалистам"),
                    ("gift", "Подарочные коды"),
                    ("adjustment", "Корректировки"),
                    ("company_budget", "Бюджет компании (B2B)"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ledgertransaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("topup", "Пополнение"),
                    ("topup_refund", "Возврат пополнения на карту"),
                    ("topup_refund_reversal", "Отмена возврата"),
                    ("hold", "Оплата созвона (заморозка)"),
                    ("capture", "Созвон состоялся"),
                    ("release", "Возврат за созвон"),
                    ("call_refund", "Возврат за состоявшийся созвон"),
                    ("mature", "Заработок доступен"),
                    ("payout_request", "Запрос выплаты"),
                    ("payout_paid", "Выплата отправлена"),
                    ("payout_return", "Выплата отклонена"),
                    ("gift_redeem", "Подарочный код"),
                    ("adjustment", "Корректировка"),
                    ("company_topup", "Пополнение бюджета компании"),
                    ("company_adjustment", "Корректировка бюджета компании"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
