/**
 * Background decoration for genuinely empty spots: 1–3 happy HEADZ avatars with
 * floating hands (pre-rendered transparent WebP in public/decor/, generated by
 * scripts/render-decor.mjs from /dev/avatar-decor — no WebGL on the page).
 *
 * Purely decorative: aria-hidden, no pointer events, absolutely positioned by the
 * caller's `className` (the parent must be position: relative), lazy, fixed size
 * (no layout shift), a gentle float that stops with prefers-reduced-motion, and
 * hidden below `from` px where there is no empty space.
 */
import s from "./decor.module.css";

export const DECOR_PICS = ["wave", "thumbs", "peace", "hello", "yay"] as const;
export type DecorPic = (typeof DECOR_PICS)[number];

export function AvatarDecor({
  pics,
  size = 200,
  from = 1024,
  className,
}: {
  /** first is the main one; the others are smaller companions to its left */
  pics: DecorPic[];
  /** CSS px of the main picture (square) */
  size?: number;
  /** shown only at viewport widths ≥ this */
  from?: 1024 | 1200;
  className?: string;
}) {
  const list = pics.slice(0, 3);
  return (
    <div aria-hidden className={`${s.decor} ${from === 1200 ? s.from1200 : s.from1024} ${className ?? ""}`}>
      {list.map((p, i) => {
        const px = Math.round(size * (i === 0 ? 1 : 0.7));
        return (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            key={p + i}
            src={`/decor/${p}.webp`}
            alt=""
            width={px}
            height={px}
            loading="lazy"
            decoding="async"
            draggable={false}
            className={s.pic}
            style={{ animationDelay: `${-i * 2.3}s`, order: -i }}
          />
        );
      })}
    </div>
  );
}
