# Generated by Django 5.0.6 on 2026-09-26 03:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0004_psychologist_gender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("text", models.TextField(blank=True, default="", max_length=2000)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Опубликован"),
                            ("hidden", "Скрыт модератором"),
                        ],
                        db_index=True,
                        default="published",
                        max_length=12,
                    ),
                ),
                (
                    "hidden_reason",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "reply_text",
                    models.TextField(blank=True, default="", max_length=1500),
                ),
                ("reply_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_written",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hidden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="users.psychologistprofile",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_review",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["psychologist", "status", "created_at"],
                        name="reviews_rev_psychol_3eaa3b_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("psychologist", "client"), name="review_one_per_client"
            ),
        ),
    ]
