# Generated by Django 5.0.6 on 2026-09-26 03:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0004_psychologist_gender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("diploma", "Диплом о высшем образовании"),
                            ("retraining", "Переподготовка, ДПО"),
                            ("method", "Сертификат метода"),
                            ("supervision", "Супервизия"),
                            ("membership", "Членство в ассоциации"),
                            ("publication", "Публикация"),
                            ("course", "Курс или тренинг"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("issuer", models.CharField(blank=True, default="", max_length=200)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("year_end", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "supervisor",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("hours", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("url", models.URLField(blank=True, default="", max_length=500)),
                ("doi", models.CharField(blank=True, default="", max_length=120)),
                ("number_enc", models.BinaryField(blank=True, default=b"")),
                ("number_hint", models.CharField(blank=True, default="", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На проверке"),
                            ("approved", "Подтверждено"),
                            ("rejected", "Отклонено"),
                            ("needs_info", "Требует уточнения"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "reject_reason",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("was_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="users.psychologistprofile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "credentials_credential",
                "ordering": ["-year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CredentialFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name_enc", models.BinaryField(blank=True, default=b"")),
                ("mime", models.CharField(max_length=40)),
                ("size", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("data_enc", models.BinaryField()),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="credentials.credential",
                    ),
                ),
            ],
            options={
                "db_table": "credentials_file",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CredentialNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_role",
                    models.CharField(
                        choices=[
                            ("staff", "Команда"),
                            ("specialist", "Специалист"),
                            ("system", "Система"),
                        ],
                        max_length=12,
                    ),
                ),
                ("text", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="credentials.credential",
                    ),
                ),
            ],
            options={
                "db_table": "credentials_note",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="credential",
            index=models.Index(
                fields=["status", "submitted_at"], name="credentials_status_07ce6b_idx"
            ),
        ),
    ]
