# Generated by Django 5.0.6 on 2026-09-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="number_public",
            field=models.BooleanField(default=False),
        ),
    ]
