# Generated by Django 5.0.6 on 2026-09-24 22:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consultations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blocked", models.BooleanField(default=False)),
                (
                    "block_reason",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("blocked_at", models.DateTimeField(blank=True, null=True)),
                ("tokens_valid_after", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "staff_account_status",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_alias",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("actor_role", models.CharField(blank=True, default="", max_length=20)),
                ("action", models.CharField(db_index=True, max_length=60)),
                (
                    "target_type",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "target_label",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись журнала",
                "db_table": "staff_audit_log",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Владелец"),
                            ("admin", "Администратор"),
                            ("moderator", "Модератор"),
                            ("support", "Поддержка"),
                            ("developer", "Разработчик"),
                            ("editor", "Редактор"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("must_change_password", models.BooleanField(default=False)),
                ("totp_secret_encrypted", models.TextField(blank=True, default="")),
                ("totp_pending_encrypted", models.TextField(blank=True, default="")),
                ("totp_enabled", models.BooleanField(default=False)),
                ("totp_last_step", models.BigIntegerField(default=0)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "db_table": "staff_member",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("user", "Пользователь"),
                            ("specialist", "Специалист"),
                            ("session", "Сессия"),
                            ("message", "Сообщение"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_message_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("abuse", "Оскорбления или угрозы"),
                            ("harassment", "Преследование"),
                            ("spam", "Спам или реклама"),
                            ("fraud", "Мошенничество"),
                            ("unprofessional", "Непрофессиональное поведение"),
                            ("inappropriate", "Недопустимый контент"),
                            ("safety", "Угроза жизни или безопасности"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="", max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Новая"),
                            ("in_review", "В работе"),
                            ("resolved", "Решена"),
                            ("dismissed", "Отклонена"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "resolution_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "Без мер"),
                            ("warn", "Предупреждение"),
                            ("block_user", "Блокировка аккаунта"),
                            ("suspend_specialist", "Приостановка специалиста"),
                            ("cancel_session", "Отмена сессии"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(blank=True, default="", max_length=1000),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="consultations.consultationsession",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "staff_report",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="staff_repor_status_56d772_idx",
                    )
                ],
            },
        ),
    ]
