# Generated by Django 5.0.6 on 2026-09-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_existing_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("user", "Пользователь"),
                    ("specialist", "Специалист"),
                    ("session", "Сессия"),
                    ("message", "Сообщение"),
                    ("review", "Отзыв"),
                ],
                max_length=20,
            ),
        ),
    ]
